version: '3.0'

services:
  salic-mssql:
    build: .
    image: culturagovbr/salic-mssql:1.1.0
    container_name: salic-mssql
    volumes: 
      # - docker-data:/var/opt/mssql # for mac
      - ./docker-data:/var/opt/mssql # for linux
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=salic@123456
      - MSSQL_PID=Developer
      - RESTAURAR_BACKUP=true
      - GERAR_ESTRUTURA_E_DADOS=false
      - MIGRAR_DADOS_COM_PYTHON=false
 
# volumes: # for mac
  # docker-data: 

    