INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(7, 'Público', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(7, 'Privado com fins lucrativo', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(8, 'Municipal', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(8, 'Estadual', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(8, 'Federal', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(9, 'Executivo', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(9, 'Legislativo', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(9, 'Judiciário', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(10, 'Direta', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(10, 'Indireta', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'ONG', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'OSCIP', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Órgão Gestor de Cultura', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(1, 'Nome de Registro', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(1, 'Razão Social', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(1, 'Nome Fantasia', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(1, 'Apelido', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(2, 'Residencial', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(2, 'Comercial', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(3, 'Residencial', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(3, 'Comercial', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(3, 'Celular', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(3, 'Fax', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(4, 'E-mail Particular', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(4, 'E-mail Institucional', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(5, 'Carteira de Identidade', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(5, 'Título de Eleitor', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(7, 'Privado sem fins lucrativo', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(4, 'Blog', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(4, 'Orkut', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(4, 'Site', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(1, 'Nome Artístico', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Avenida', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Praça', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Quadra', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Rua', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Outros', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Prefeitura', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Biblioteca', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Ponto de Cultura', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado de Cultura', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Museu', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Instituto', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Fundação', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Forum de Cultura', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Secretaria', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Empresa', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Griôs', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Vago', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Departamento', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Agência', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Órgão de Administração Municipal', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Órgão de Administração Estadual', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Órgão de Administração Federal', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Largo', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Alameda', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Ladeira', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Empresa Privada', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado de Patrimônio Cultural', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Artes', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado de Incentivo à Cultura', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Artes Visuais', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Artes Cênicas', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Artes do Espetáculo', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Música', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Dança', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Teatro', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Circo', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial do Audiovisual', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial do Livro e Leitura', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Museus e Arquivos', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Museu(s)', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Arquivo(s)', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Biblioteca(s) Pública(s)', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Centro(s) Cultural(is)', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Região Urbana', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Micro/Mesorregião', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Distrito Municipal', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Órgao Consultivo/Deliberativo de Cultura', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Culturas Indígenas', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial de Culturas Afro-Brasileira', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Conselho/Órgão Colegiado Setorial da Cultura GLTB', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Empresa', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Empresa Pública', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Servidor Público', 3);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Servidor Público Federal', 3);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Servidor Público Estadual', 3);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Servidor Público Municipal', 3);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Servidor do Programa Monumenta', 3);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Servidor Consultor de Órgão Internacional', 3);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Servidor Vigilante', 3);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Servidor Motorista', 3);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Aeroporto', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Área', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Campo', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Chácara', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Colônia', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Condomínio', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Conjunto', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Distrito', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Esplanada', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Estação', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Estrada', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Favela', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Fazenda', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Feira', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Jardim', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Lago', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Lagoa', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Loteamento', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Morro', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Núcleo', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Parque', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Passarela', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Pátio', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Recanto', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Residência', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Rodovia', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Setor', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Sítio', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Travessa', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Trecho', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Vale', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Vereda', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Via', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Viaduto', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Viela', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(13, 'Vila', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Proponente', 21);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Incentivador', 21);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Servidor', 21);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Prestadores de Serviços', 3);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Servidor de Limpeza', 3);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Órgãos de Cultura', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Conselho', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Órgão Colegiado Setorial', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Órgão Colegiado', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Órgao Consultivo', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Órgão Deliberativo', 13);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Operadora do Ticket Cultural', 4);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Doadora do Ticket Cultural', 4);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(17, 'Certidão de Quitação de Tributos Municipais', 12);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(17, 'Certidão de Quitação de Tributos Estaduais', 12);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(17, 'Certidão Conjunta Negativa de Tributos Federais e Dívida Ativa da União', 12);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(17, 'Certidão Negativa de Débitos junto ao INSS', 12);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(17, 'Certidão Negativa de Débitos junto ao FGTS', 12);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Poder Executivo Municipal', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Poder Executivo Estadual', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Poder Executivo Federal', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Cadastro', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(11, 'Nenhum', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(1, 'Sigla', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Cultura Viva', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Mala Direta', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(4, 'Grupo de e-mail', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(5, 'Registro Profissional', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(5, 'Carteira de Trabalho', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Diversidade Cultural', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Inclusão Cultural da Pessoa Idosa', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Governo Estadual', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Governo Federal', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(20, 'Ficha de inscrição devidamente preenchida', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(18, 'Cópia autenticada da carteira de identidade', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(18, 'Cópia autenticada do CPF', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(18, 'Curriculum Vitae', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(20, 'Carta de recomendação de autoridade na área cultural endossando a iniciativa', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(20, 'Material complementar sobre a iniciativa: matérias de jornal, DVDs, CDs, fotos, folders, cartazes', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(19, 'Cópia autenticada do estatuto da instituição e alterações, se houver', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(19, 'Cópia autenticada do termo de posse do dirigente em exercício', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(19, 'Cópia autenticada do cartão do CNPJ', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(19, 'Cópia autenticada da carteira de identidade do dirigente em exercício', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(19, 'Cópia autenticada do CPF do dirigente em exercício', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(19, 'Relatório das atividades da instituição na área cultural', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Prêmio Culturas Ciganas', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Prêmio Culturas Populares', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(19, 'Cópia autenticada da última alteração', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(20, 'Termo de responsabilidade assinado', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Parceiro de Projeto Cultural', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Dirigente de Instituição', 21);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Beneficiário de produtos do projeto cultural', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Interviniente', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(20, 'Cópia autenticada de comprovante de endereço atualizado', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(20, 'Proponente habilitado de acordo com o edital', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Vago', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Seção', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Coordenação', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Gerência', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Divisão', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(14, 'Diretoria', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Parecerista de projeto cultural', 21);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Componente da Comissão', 21);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Avaliador de Edital', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Representantes na CNIC', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Coord Acompanhamento', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Coord Parecerista', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Vago', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Tecnico', 21);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(16, 'Votantes da Cnic', 21);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(21, 'Ensino Fundamental', 0);
INSERT INTO Agentes.dbo.Verificacao (IdTipo, Descricao, Sistema) VALUES(21, 'Ensino Médio', 0);