INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(1,' ','Afeganistão','Ásia')
,(2,' ','África do Sul','África')
,(3,' ','Alasca','América do Norte')
,(4,' ','Albânia','Europa')
,(5,' ','Alemanha','Europa')
,(6,' ','Andorra','Europa')
,(7,' ','Angola','África')
,(8,' ','Anguilla','América Central')
,(9,' ','Ant.Holandesas','América Central')
,(10,' ','Antigua','América Central')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(11,' ','Arábia Saudita','Ásia')
,(12,' ','Argélia','África')
,(13,' ','Argentina','América do Sul')
,(14,' ','Armênia','Europa')
,(15,' ','Aruba','América Central')
,(16,' ','Austrália','Oceania')
,(17,' ','Áustria','Europa')
,(18,' ','Azerbaijão','Europa')
,(19,' ','Bahamas','América Central')
,(20,' ','Bangladesh','Ásia')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(21,' ','Barbados','América Central')
,(22,' ','Barein','Ásia')
,(23,' ','Belarus','Europa')
,(24,' ','Bélgica','Europa')
,(25,' ','Belize','América Central')
,(26,' ','Benin','África')
,(27,' ','Bermudas','América do Norte')
,(28,' ','Bolívia','América do Sul')
,(29,' ','Bósnia E Herzegovina','Europa')
,(30,' ','Botsuana','África')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(31,' ','Brasil','América do Sul')
,(32,' ','Brunei','Ásia')
,(33,' ','Bulgária','Europa')
,(34,' ','Burkina Faso','África')
,(35,' ','Burundi','África')
,(36,' ','Butão','Ásia')
,(37,' ','Cabo Verde','África')
,(38,' ','Camarões','África')
,(39,' ','Campuchea','Ásia')
,(40,' ','Canadá','América do Norte')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(41,' ','Casaquistão','Ásia')
,(42,' ','Catar','Ásia')
,(43,' ','Chade','África')
,(44,' ','Chile','América do Sul')
,(45,' ','China','Ásia')
,(46,' ','Chipre','Europa')
,(47,' ','Cingapura','Ásia')
,(48,' ','Colômbia','América do Sul')
,(49,' ','Comores','África')
,(50,' ','Congo','África')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(51,' ','Coréia do Norte','Ásia')
,(52,' ','Coréia do Sul','Ásia')
,(53,' ','Costa do Marfim','África')
,(54,' ','Costa Rica','América Central')
,(55,' ','Croácia','Europa')
,(56,' ','Cuba','América Central')
,(57,' ','Diego Garcia','Ásia')
,(58,' ','Dinamarca','Europa')
,(59,' ','Djibuti','África')
,(60,' ','Dominica','América Central')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(61,' ','Egito','África')
,(62,' ','El Salvador','América Central')
,(63,' ','Emirados A. Unidos','Ásia')
,(64,' ','Equador','América do Sul')
,(65,' ','Eritréa','África')
,(66,' ','Eslovênia','Europa')
,(67,' ','Espanha','Europa')
,(68,' ','Estados Unidos','América do Norte')
,(69,' ','Estônia','Europa')
,(70,' ','Etiópia','África')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(71,' ','Fiji','Oceania')
,(72,' ','Filipinas','Ásia')
,(73,' ','Finlândia','Europa')
,(74,' ','Formosa','Ásia')
,(75,' ','França','Europa')
,(76,' ','Gabão','África')
,(77,' ','Gâmbia','África')
,(78,' ','Gana','África')
,(79,' ','Geórgia','Europa')
,(80,' ','Gibraltar','Europa')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(81,' ','Granada','América Central')
,(82,' ','Grécia','Europa')
,(83,' ','Groelândia','América do Norte')
,(84,' ','Guadalupe','América Central')
,(85,' ','Guam','Oceania')
,(86,' ','Guatemala','América Central')
,(87,' ','Guiana','América do Sul')
,(88,' ','Guiana Francesa','América do Sul')
,(89,' ','Guiné','África')
,(90,' ','Guiné Equatorial','África')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(91,' ','Guiné-Bissau','África')
,(92,' ','Haiti','América Central')
,(93,' ','Havaí','América do Norte')
,(94,' ','Holanda','Europa')
,(95,' ','Honduras','América Central')
,(96,' ','Hong Kong','Ásia')
,(97,' ','Hungria','Europa')
,(98,' ','Ilhas Ascensão','África')
,(99,' ','Ilhas Caicos','América Central')
,(100,' ','Ilhas Cayman','América Central')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(101,' ','Ilhas Cook','Oceania')
,(102,' ','Ilhas Faroe','Europa')
,(103,' ','Ilhas Malvinas','América do Sul')
,(104,' ','Ilhas Marianas Norte','Oceania')
,(105,' ','Ilhas Marshall','Oceania')
,(106,' ','Ilhas Mayotte','África')
,(107,' ','Ilhas Midway','América do Norte')
,(108,' ','Ilhas Norfolk','Oceania')
,(109,' ','Ilhas Reunião','África')
,(110,' ','Ilhas Rodrigues','África')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(111,' ','Ilhas Salomão','Oceania')
,(112,' ','Ilhas Santa Helena','África')
,(113,' ','Ilhas Virgens','América Central')
,(114,' ','Ilhas Wake','Oceania')
,(115,' ','Índia','Ásia')
,(116,' ','Indonésia','Ásia')
,(117,' ','Irã','Ásia')
,(118,' ','Iraque','Ásia')
,(119,' ','Irlanda','Europa')
,(120,' ','Islândia','Europa')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(121,' ','Israel','Ásia')
,(122,' ','Itália','Europa')
,(123,' ','Iugoslávia','Europa')
,(124,' ','Jamaica','América Central')
,(125,' ','Japão','Ásia')
,(126,' ','Jordânia','Ásia')
,(127,' ','Kiribati','Oceania')
,(128,' ','Kuwait','Ásia')
,(129,' ','Laos','Ásia')
,(130,' ','Lesoto','África')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(131,' ','Letônia','Europa')
,(132,' ','Líbano','Ásia')
,(133,' ','Libéria','África')
,(134,' ','Líbia','África')
,(135,' ','Liechtenstein','Europa')
,(136,' ','Lituânia','Europa')
,(137,' ','Luxemburgo','Europa')
,(138,' ','Macau','Ásia')
,(139,' ','Macedônia','Europa')
,(140,' ','Madagascar','África')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(141,' ','Malásia','Ásia')
,(142,' ','Malavi','África')
,(143,' ','Maldivas','Ásia')
,(144,' ','Mali','África')
,(145,' ','Malta','Europa')
,(146,' ','Marrocos','África')
,(147,' ','Martiníca','América Central')
,(148,' ','Maurício','África')
,(149,' ','Mauritânia','África')
,(150,' ','México','América do Norte')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(151,' ','Micronésia','Oceania')
,(152,' ','Moçambique','África')
,(153,' ','Moldova','Europa')
,(154,' ','Mongólia','Ásia')
,(155,' ','Montserrat','América Central')
,(156,' ','Namíbia','África')
,(157,' ','Nauru','Oceania')
,(158,' ','Nepal','Ásia')
,(159,' ','Nicarágua','América Central')
,(160,' ','Niger','África')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(161,' ','Nigéria','África')
,(162,' ','Niue','Oceania')
,(163,' ','Noruega','Europa')
,(164,' ','Nova Caledônia','Oceania')
,(165,' ','Nova Zelândia','Oceania')
,(166,' ','Omã','Ásia')
,(167,' ','Palau','Oceania')
,(168,' ','Palestina','Ásia')
,(169,' ','Panamá','América Central')
,(170,' ','Papua Nova Guiné','Oceania')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(171,' ','Paquistão','Ásia')
,(172,' ','Paraguai','América do Sul')
,(173,' ','Peru','América do Sul')
,(174,' ','Polônia','Europa')
,(175,' ','Porto Rico','América Central')
,(176,' ','Portugal','Europa')
,(177,' ','Principado Mônaco','Europa')
,(178,' ','Quênia','África')
,(179,' ','Quirguizia','Ásia')
,(180,' ','Reino Unido','Europa')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(181,' ','Rep. Centro Africana','África')
,(182,' ','Rep. Eslováquia','Europa')
,(183,' ','Rep. Tcheca','Europa')
,(184,' ','República do Iemen','Ásia')
,(185,' ','República Dominicana','América Central')
,(186,' ','Romênia','Europa')
,(187,' ','Ruanda','África')
,(188,' ','Rússia','Europa')
,(189,' ','S.Kitts e Nevis','América Central')
,(190,' ','S.Vicente Ilhas','América Central')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(191,' ','Saara Espanhol','África')
,(192,' ','Samoa','Oceania')
,(193,' ','Samoa Americana','Oceania')
,(194,' ','Santa Lucia','América Central')
,(195,' ','São Marino','Europa')
,(196,' ','São Tomé e Principe','África')
,(197,' ','Senegal','África')
,(198,' ','Serra Leoa','África')
,(199,' ','Seychelles','África')
,(200,' ','Síria','Ásia')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(201,' ','Somália','África')
,(202,' ','Sri-Lanka','Ásia')
,(203,' ','St.Pierre e Miquelon','Ámerica do Norte')
,(204,' ','Suazilândia','África')
,(205,' ','Sudão','África')
,(206,' ','Suécia','Europa')
,(207,' ','Suíça','Europa')
,(208,' ','Suriname','América do Sul')
,(209,' ','Tadjiquistão','Ásia')
,(210,' ','Tailândia','Ásia')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(211,' ','Taiti','Oceania')
,(212,' ','Tanzânia','África')
,(213,' ','Territ. ext. Austrália','Oceania')
,(214,' ','Timor Leste','Oceania')
,(215,' ','Togo','África')
,(216,' ','Tonga','Oceania')
,(217,' ','Toquelau','Oceania')
,(218,' ','Trinidad e Tobago','América Central')
,(219,' ','Tunísia','África')
,(220,' ','Turcomenia','Ásia')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(221,' ','Turquia','Europa')
,(222,' ','Tuvalu','Oceania')
,(223,' ','Ucrânia','Europa')
,(224,' ','Uganda','África')
,(225,' ','União de Myanmar','Ásia')
,(226,' ','Uruguai','América do Sul')
,(227,' ','Uzbequistão','Ásia')
,(228,' ','Vanuatu','Oceania')
,(229,' ','Venezuela','América do Sul')
,(230,' ','Vietnã','Ásia')
;
INSERT INTO Agentes.dbo.Pais (idPais,Sigla,Descricao,Continente) VALUES
(231,' ','Ilhas Virgens Britânicas','Europa')
,(232,' ','Wallis e Futuna','Oceania')
,(233,' ','Zaire','África')
,(234,' ','Zâmbia','África')
,(235,' ','Zanzibar','África')
,(236,' ','Zimbábue','África')
;