INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('11001', 'Porto Velho');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('11002', 'Guajará-Mirim');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('11003', 'Ariquemes');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('11004', 'Ji-Paraná');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('11005', 'Alvorada D''Oeste');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('11006', 'Cacoal');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('11007', 'Vilhena');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('11008', 'Colorado do Oeste');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('12001', 'Cruzeiro do Sul');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('12002', 'Tarauacá');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('12003', 'Sena Madureira');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('12004', 'Rio Branco');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('12005', 'Brasiléia');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('13001', 'Rio Negro');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('13002', 'Japurá');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('13003', 'Alto Solimões');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('13004', 'Juruá');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('13005', 'Tefé');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('13006', 'Coari');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('13007', 'Manaus');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('13008', 'Rio Preto da Eva');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('13009', 'Itacoatiara');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('13010', 'Parintins');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('13011', 'Boca do Acre');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('13012', 'Purus');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('13013', 'Madeira');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('14001', 'Boa Vista');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('14002', 'Nordeste de Roraima');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('14003', 'Caracaraí');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('14004', 'Sudeste de Roraima');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15001', 'Óbidos');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15002', 'Santarém');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15003', 'Almeirim');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15004', 'Portel');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15005', 'Furos de Breves');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15006', 'Arari');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15007', 'Belém');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15008', 'Castanhal');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15009', 'Salgado');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15010', 'Bragantina');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15011', 'Cametá');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15012', 'Tomé-Açu');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15013', 'Guamá');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15014', 'Itaituba');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15015', 'Altamira');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15016', 'Tucuruí');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15017', 'Paragominas');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15018', 'São Félix do Xingu');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15019', 'Parauapebas');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15020', 'Marabá');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15021', 'Redenção');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('15022', 'Conceição do Araguaia');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('16001', 'Oiapoque');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('16002', 'Amapá');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('16003', 'Macapá');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('16004', 'Mazagão');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('17001', 'Bico do Papagaio');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('17002', 'Araguaína');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('17003', 'Miracema do Tocantins');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('17004', 'Rio Formoso');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('17005', 'Gurupi');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('17006', 'Porto Nacional');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('17007', 'Jalapão');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('17008', 'Dianópolis');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21001', 'Litoral Ocidental Maranhense');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21002', 'Aglomeração Urbana de São Luís');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21003', 'Rosário');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21004', 'Lençois Maranhenses');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21005', 'Baixada Maranhense');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21006', 'Itapecuru Mirim');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21007', 'Gurupi');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21008', 'Pindaré');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21009', 'Imperatriz');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21010', 'Médio Mearim');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21011', 'Alto Mearim e Grajaú');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21012', 'Presidente Dutra');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21013', 'Baixo Parnaíba Maranhense');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21014', 'Chapadinha');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21015', 'Codó');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21016', 'Coelho Neto');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21017', 'Caxias');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21018', 'Chapadas do Alto Itapecuru');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21019', 'Porto Franco');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21020', 'Gerais de Balsas');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('21021', 'Chapadas das Mangabeiras');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22001', 'Baixo Parnaíba Piauiense');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22002', 'Litoral Piauiense');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22003', 'Teresina');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22004', 'Campo Maior');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22005', 'Médio Parnaíba Piauiense');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22006', 'Valença do Piauí');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22007', 'Alto Parnaíba Piauiense');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22008', 'Bertolínia');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22009', 'Floriano');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22010', 'Alto Médio Gurguéia');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22011', 'São Raimundo Nonato');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22012', 'Chapadas do Extremo Sul Piauiense');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22013', 'Picos');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22014', 'Pio IX');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('22015', 'Alto Médio Canindé');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23001', 'Litoral de Camocim e Acaraú');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23002', 'Ibiapaba');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23003', 'Coreaú');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23004', 'Meruoca');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23005', 'Sobral');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23006', 'Ipu');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23007', 'Santa Quitéria');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23008', 'Itapipoca');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23009', 'Baixo Curu');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23010', 'Uruburetama');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23011', 'Médio Curu');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23012', 'Canindé');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23013', 'Baturité');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23014', 'Chorozinho');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23015', 'Cascavel');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23016', 'Fortaleza');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23017', 'Pacajus');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23018', 'Sertão de Cratéus');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23019', 'Sertão de Quixeramobim');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23020', 'Sertão de Inhamuns');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23021', 'Sertão de Senador Pompeu');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23022', 'Litoral de Aracati');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23023', 'Baixo Jaguaribe');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23024', 'Médio Jaguaribe');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23025', 'Serra do Pereiro');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23026', 'Iguatu');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23027', 'Várzea Alegre');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23028', 'Lavras da Mangabeira');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23029', 'Chapada do Araripe');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23030', 'Caririaçu');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23031', 'Barro');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23032', 'Cariri');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('23033', 'Brejo Santo');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24001', 'Mossoró');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24002', 'Chapada do Apodi');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24003', 'Médio Oeste');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24004', 'Vale do Açu');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24005', 'Serra de São Miguel');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24006', 'Pau dos Ferros');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24007', 'Umarizal');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24008', 'Macau');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24009', 'Angicos');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24010', 'Serra de Santana');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24011', 'Seridó Ocidental');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24012', 'Seridó Oriental');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24013', 'Baixa Verde');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24014', 'Borborema Potiguar');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24015', 'Agreste Potiguar');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24016', 'Litoral Nordeste');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24017', 'Macaíba');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24018', 'Natal');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('24019', 'Litoral Sul');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25001', 'Catolé do Rocha');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25002', 'Cajazeiras');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25003', 'Sousa');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25004', 'Patos');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25005', 'Piancó');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25006', 'Itaporanga');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25007', 'Serra do Teixeira');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25008', 'Seridó Ocidental Paraibano');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25009', 'Seridó Oriental Paraibano');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25010', 'Cariri Ocidental');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25011', 'Cariri Oriental');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25012', 'Curimataú Ocidental');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25013', 'Curimataú Oriental');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25014', 'Esperança');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25015', 'Brejo Paraibano');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25016', 'Guarabira');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25017', 'Campina Grande');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25018', 'Itabaiana');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25019', 'Umbuzeiro');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25020', 'Litoral Norte');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25021', 'Sapé');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25022', 'João Pessoa');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('25023', 'Litoral Sul');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26001', 'Araripina');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26002', 'Salgueiro');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26003', 'Pajeú');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26004', 'Sertão do Moxotó');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26005', 'Petrolina');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26006', 'Itaparica');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26007', 'Vale do Ipanema');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26008', 'Vale do Ipojuca');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26009', 'Alto Capibaribe');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26010', 'Médio Capibaribe');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26011', 'Garanhuns');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26012', 'Brejo Pernambucano');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26013', 'Mata Setentrional Pernambucana');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26014', 'Vitória de Santo Antão');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26015', 'Mata Meridional Pernambucana');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26016', 'Itamaracá');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26017', 'Recife');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26018', 'Suape');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('26019', 'Fernando de Noronha');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('27001', 'Serrana do Sertão Alagoano');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('27002', 'Alagoana do Sertão do São Francisco');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('27003', 'Santana do Ipanema');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('27004', 'Batalha');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('27005', 'Palmeira dos Índios');
INSERT INTO Agentes.dbo.MicroRegiao (idMicro, descricao) VALUES('27006', 'Arapiraca');
