INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1101', 'Madeira-Guaporé');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1102', 'Leste Rondoniense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1201', 'Vale do Juruá');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1202', 'Vale do Acre');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1301', 'Norte Amazonense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1302', 'Sudoeste Amazonense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1303', 'Centro Amazonense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1304', 'Sul Amazonense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1401', 'Norte de Roraima');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1402', 'Sul de Roraima');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1501', 'Baixo Amazonas');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1502', 'Marajó');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1503', 'Metropolitana de Belém');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1504', 'Nordeste Paraense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1505', 'Sudoeste Paraense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1506', 'Sudeste Paraense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1601', 'Norte do Amapá');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1602', 'Sul do Amapá');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1701', 'Ocidental do Tocantins');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('1702', 'Oriental do Tocantins');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2101', 'Norte Maranhense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2102', 'Oeste Maranhense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2103', 'Centro Maranhense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2104', 'Leste Maranhense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2105', 'Sul Maranhense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2201', 'Norte Piauiense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2202', 'Centro-Norte Piauiense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2203', 'Sudoeste Piauiense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2204', 'Sudeste Piauiense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2301', 'Noroeste Cearense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2302', 'Norte Cearense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2303', 'Metropolitana de Fortaleza');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2304', 'Sertões Cearenses');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2305', 'Jaguaribe');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2306', 'Centro-Sul Cearense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2307', 'Sul Cearense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2401', 'Oeste Potiguar');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2402', 'Central Potiguar');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2403', 'Agreste Potiguar');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2404', 'Leste Potiguar');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2501', 'Sertão Paraibano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2502', 'Borborema');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2503', 'Agreste Paraibano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2504', 'Mata Paraibana');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2601', 'Sertão Pernambucano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2602', 'São Francisco Pernambucano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2603', 'Agreste Pernambucano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2604', 'Mata Pernambucana');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2605', 'Metropolitana de Recife');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2701', 'Sertão Alagoano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2702', 'Agreste Alagoano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2703', 'Leste Alagoano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2801', 'Sertão Sergipano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2802', 'Agreste Sergipano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2803', 'Leste Sergipano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2901', 'Extremo Oeste Baiano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2902', 'Vale São-Franciscano da Bahia');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2903', 'Centro Norte Baiano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2904', 'Nordeste Baiano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2905', 'Metropolitana de Salvador');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2906', 'Centro Sul Baiano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('2907', 'Sul Baiano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3101', 'Noroeste de Minas');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3102', 'Norte de Minas');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3103', 'Jequitinhonha');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3104', 'Vale do Mucuri');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3105', 'Triângulo Mineiro/Alto Paranaíba');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3106', 'Central Mineira');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3107', 'Metropolitana de Belo Horizonte');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3108', 'Vale do Rio Doce');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3109', 'Oeste de Minas');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3110', 'Sul/Sudoeste de Minas');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3111', 'Campo das Vertentes');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3112', 'Zona da Mata');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3201', 'Noroeste Espírito-santense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3202', 'Litoral Norte Espírito-santense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3203', 'Central Espírito-santense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3204', 'Sul Espírito-santense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3301', 'Noroeste Fluminense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3302', 'Norte Fluminense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3303', 'Centro Fluminense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3304', 'Baixadas');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3305', 'Sul Fluminense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3306', 'Metropolitana do Rio de Janeiro');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3501', 'São José do Rio Preto');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3502', 'Ribeirão Preto');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3503', 'Araçatuba');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3504', 'Bauru');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3505', 'Araraquara');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3506', 'Piracicaba');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3507', 'Campinas');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3508', 'Presidente Prudente');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3509', 'Marília');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3510', 'Assis');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3511', 'Itapetininga');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3512', 'Macro Metropolitana Paulista');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3513', 'Vale do Paraíba Paulista');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3514', 'Litoral Sul Paulista');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('3515', 'Metropolitana de São Paulo');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4101', 'Noroeste Paranaense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4102', 'Centro Ocidental Paranaense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4103', 'Norte Central Paranaense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4104', 'Norte Pioneiro Paranaense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4105', 'Centro Oriental Paranaense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4106', 'Oeste Paranaense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4107', 'Sudoeste Paranaense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4108', 'Centro-Sul Paranaense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4109', 'Sudeste Paranaense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4110', 'Metropolitana de Curitiba');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4201', 'Oeste Catarinense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4202', 'Norte Catarinense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4203', 'Serrana');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4204', 'Vale do Itajaí');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4205', 'Grande Florianópolis');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4206', 'Sul Catarinense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4301', 'Noroeste Rio-grandense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4302', 'Nordeste Rio-grandense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4303', 'Centro Ocidental Rio-grandense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4304', 'Centro Oriental Rio-grandense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4305', 'Metropolitana de Porto Alegre');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4306', 'Sudoeste Rio-grandense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('4307', 'Sudeste Rio-grandense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5001', 'Pantanais Sul Mato-grossense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5002', 'Centro Norte de Mato Grosso do Sul');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5003', 'Leste de Mato Grosso do Sul');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5004', 'Sudoeste de Mato Grosso do Sul');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5101', 'Norte Mato-grossense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5102', 'Nordeste Mato-grossense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5103', 'Sudoeste Mato-grossense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5104', 'Centro-Sul Mato-grossense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5105', 'Sudeste Mato-grossense');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5201', 'Noroeste Goiano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5202', 'Norte Goiano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5203', 'Centro Goiano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5204', 'Leste Goiano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5205', 'Sul Goiano');
INSERT INTO Agentes.dbo.MesoRegiao (idMeso, descricao) VALUES('5301', 'Distrito Federal');