INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(11, 'RO', 'Rondônia', 'Norte');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(12, 'AC', 'Acre', 'Norte');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(13, 'AM', 'Amazonas', 'Norte');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(14, 'RR', 'Roraima', 'Norte');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(15, 'PA', 'Pará', 'Norte');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(16, 'AP', 'Amapá', 'Norte');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(17, 'TO', 'Tocantins', 'Norte');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(21, 'MA', 'Maranhão', 'Nordeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(22, 'PI', 'Piauí', 'Nordeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(23, 'CE', 'Ceará', 'Nordeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(24, 'RN', 'Rio Grande do Norte', 'Nordeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(25, 'PB', 'Paraíba', 'Nordeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(26, 'PE', 'Pernambuco', 'Nordeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(27, 'AL', 'Alagoas', 'Nordeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(28, 'SE', 'Sergipe', 'Nordeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(29, 'BA', 'Bahia', 'Nordeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(31, 'MG', 'Minas Gerais', 'Sudeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(32, 'ES', 'Espírito Santo', 'Sudeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(33, 'RJ', 'Rio de Janeiro', 'Sudeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(35, 'SP', 'São Paulo', 'Sudeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(41, 'PR', 'Paraná', 'Sul');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(42, 'SC', 'Santa Catarina', 'Sul');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(43, 'RS', 'Rio Grande do Sul', 'Sul');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(50, 'MS', 'Mato Grosso do Sul', 'Centro Oeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(51, 'MT', 'Mato Grosso', 'Centro Oeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(52, 'GO', 'Goiás', 'Centro Oeste');
INSERT INTO Agentes.dbo.UF (idUF, Sigla, Descricao, Regiao) VALUES(53, 'DF', 'Distrito Federal', 'Centro Oeste');
