INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(59, 1, 'A do Cruzeiro                                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(60, 1, 'B Grande                                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(74, 1, 'J Esperança                                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(75, 1, 'J Tropical                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(79, 2, 'O D''Agua dos Cajuzinhos                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(79, 3, 'Olho D dos Cajuzinhos                                                   ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(82, 2, 'Poço Frio                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(82, 3, 'Zélia Barbosa                                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(82, 4, 'Zélia Rocha                                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(84, 1, 'Rosa Cruz                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(84, 2, 'Edwiges                                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(85, 1, 'Sta Esmeralda                                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(87, 1, 'Sen Arnon de Melo                                                       ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(87, 2, 'Sen A de Melo                                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(87, 3, 'Senador A de Melo                                                       ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(88, 1, 'Sen Teotônio Vilela                                                     ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(88, 2, 'Sen T Vilela                                                            ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(88, 3, 'Senador T Vilela                                                        ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(90, 1, 'Alberto Santos Dumont                                                   ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(90, 2, 'Loteamento Santos Dumont                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(90, 4, 'Alberto S Dumont                                                        ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(90, 5, 'A Santos Dumont                                                         ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(91, 1, 'Loteamento Terra de Antares                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(91, 2, 'Terra de Antares I                                                      ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(91, 3, 'Terra de Antares II                                                     ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(92, 2, 'Novo Mundo                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(95, 1, 'Conjunto Benedito Bentes                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(95, 2, 'Benedito Bentes I                                                       ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(95, 3, 'Benedito Bentes II                                                      ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(95, 4, 'Biu                                                                     ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(98, 1, 'Comércio                                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(99, 1, 'C da Jaqueira                                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(99, 3, 'Chã                                                                     ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(102, 1, 'Bela Vista                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(104, 1, 'Floriano Peixoto                                                        ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(104, 2, 'Floriano                                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(104, 3, 'Saúde                                                                   ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(105, 1, 'G de Lourdes                                                            ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(105, 2, 'Gruta                                                                   ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(108, 3, 'Conjunto José da Silva Peixoto                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(108, 4, 'Piabas                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(109, 1, 'Jaraguá Mirim                                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(110, 1, 'Stela Maris                                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(111, 1, 'Mercado                                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(112, 1, 'Jardim Vaticano                                                         ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(115, 1, 'Pajussara                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(116, 1, 'Sanatório                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(116, 2, 'Vila Saem                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(118, 1, 'Reginaldo                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(118, 3, 'Santo Eduardo                                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(119, 1, 'Santuário                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(119, 2, 'Santuário de Fátima                                                     ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(119, 3, 'P da Terra                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(120, 1, 'Coréia                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(122, 2, 'Pontal                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(122, 3, 'P da Barra                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(124, 1, 'Mirante                                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(124, 2, 'Mirante da Sereia                                                       ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(126, 1, 'Loteamento Santa Amélia                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(126, 2, 'Lot Santa Amélia                                                        ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(126, 3, 'Estrada de Santa Amélia                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(126, 4, 'Lot S Amélia                                                            ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(128, 2, 'Conjunto José Tenório                                                   ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(128, 3, 'Estrada da Serraria                                                     ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(129, 1, 'Tabuleiro                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(129, 2, 'Tabuleiro dos Martins                                                   ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(129, 3, 'Tabuleiro Novo                                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(129, 4, 'Tab dos Martins                                                         ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(130, 1, 'Trapiche                                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(130, 2, 'T da Barra                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(131, 1, 'Conjunto Joaquim Leão                                                   ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(131, 2, 'Vergel                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(131, 3, 'Vegel                                                                   ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(131, 4, 'V do Lago                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(131, 5, 'Conjunto Virgem dos Pobres                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(131, 6, 'Vila Kennedy                                                            ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(132, 2, 'A do Cruzeiro                                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(134, 1, 'Eucaliptos                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(135, 1, 'J Brasil                                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(137, 1, 'P de Fora                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(144, 1, 'V Maria                                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(147, 1, 'Vila Municipal                                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(151, 1, 'Arm Mendes                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(151, 2, 'A Mendes                                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(155, 1, 'Chapada Flores                                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(157, 1, 'Colônia A Aleixo                                                        ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(157, 2, 'C Antônio Aleixo                                                        ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(158, 1, 'Colônia O Machado                                                       ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(158, 2, 'Oliveira Machado                                                        ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(159, 1, 'Colônia S Antônio                                                       ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(160, 1, 'Colônia T Nova                                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(161, 1, 'Bairro da Compensa                                                      ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(163, 1, 'Crespo São Lazaro                                                       ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(164, 1, 'D Industrial                                                            ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(164, 2, 'Distrito Industrial da Zona Franca                                      ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(165, 1, 'D Pedro                                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(165, 2, 'Dom Pedro I                                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(166, 1, 'Cidade Alta                                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(167, 1, 'Fls                                                                     ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(169, 1, 'Japiinlândia                                                            ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(170, 1, 'J Teixeira                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(170, 2, 'Jorge Teixeira I                                                        ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(170, 3, 'Jorge Teixeira II                                                       ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(170, 4, 'Jorge Teixeira III                                                      ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(170, 5, 'Jorge Teixeira IV                                                       ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(171, 1, 'L do Vale                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(172, 1, 'Mauazinho Distrito Industrial                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(173, 1, 'M das Oliveira                                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(174, 1, 'Morro                                                                   ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(174, 2, 'M da Liberdade                                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(175, 1, 'N S das Graças                                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(175, 2, 'N Senhora das Graças                                                    ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(176, 1, 'N Esperança                                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(177, 1, 'N Israel                                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(178, 1, 'Parque Dez de Novembro                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(178, 2, 'Parque X de Novembro                                                    ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(178, 3, 'P Dez Novembro                                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(182, 1, 'P Negra                                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(182, 2, 'Pontanegra                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(183, 1, 'Praça Quatorze de Janeiro                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(183, 2, 'Pça 14 de Janeiro                                                       ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(183, 3, 'Praça XIV de Janeiro                                                    ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(184, 1, 'Pres Vargas                                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(184, 2, 'P Vargas                                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(184, 3, 'Matinha                                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(185, 1, 'Vila de Puraquequara                                                    ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(188, 1, 'S Etelvina                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(189, 1, 'S Luzia                                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(190, 1, 'S Agostinho                                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(191, 1, 'S Antônio                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(192, 1, 'S Francisco                                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(193, 1, 'S Geraldo                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(194, 1, 'S Jorge                                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(195, 1, 'S J Operário                                                            ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(195, 2, 'S José                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(195, 3, 'S José Operário                                                         ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(196, 1, 'S Lazaro                                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(197, 1, 'S Raimundo                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(197, 2, 'S Rdo                                                                   ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(198, 1, 'T Neves                                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(199, 1, 'Comunidade do Tarumã                                                    ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(200, 1, 'V Buriti                                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(200, 2, 'Vila Buriti Distrito Industrial                                         ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(201, 1, 'V da Prata                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(202, 1, 'Z dos Palmares                                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(202, 2, 'Zumbi                                                                   ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(203, 1, 'Centro Comercial de Parintins                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(217, 1, 'Comercio                                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(218, 1, 'dos Congos                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(220, 1, 'J Felicidade                                                            ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(221, 1, 'J Marco Zero                                                            ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(221, 2, 'Jardim Equatorial                                                       ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(222, 1, 'J de Nazaré                                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(223, 1, 'Laguinho                                                                ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(232, 1, 'Bairro                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(233, 1, 'Bairro                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(234, 1, 'Conselheiro Junqueira                                                   ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(235, 1, 'Bairro                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(236, 1, 'Bairro                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(237, 1, 'Teresópolis                                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(238, 1, 'Bairro                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(239, 1, 'Centro                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(240, 1, 'Bairro                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(241, 1, 'Bairro Mangalô                                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(243, 1, 'Silva Jardim                                                            ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(244, 1, 'Bairro                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(245, 1, 'Bairro                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(246, 1, 'Bairro                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(247, 1, 'Bairro                                                                  ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(248, 1, 'B Vista                                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(248, 2, 'Barreirinhas                                                            ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(249, 1, 'Cj Hab Buritis I                                                        ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(249, 2, 'Buritis I                                                               ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(251, 1, 'Lot Flamengo                                                            ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(252, 1, 'Vl Juri                                                                 ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(253, 1, 'Cj Res Morada Nobre                                                     ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(253, 2, 'Lot Morada Nobre                                                        ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(255, 1, 'Lot Novo Horizonte                                                      ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(255, 2, 'Prq Novo Horizonte                                                      ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(255, 3, 'Lot N Horizonte                                                         ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(255, 4, 'Prq N Horizonte                                                         ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(256, 1, 'Lot Ouro Branco                                                         ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(258, 1, 'Lot Primavera                                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(259, 1, 'Lot Renato Gonçalves                                                    ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(260, 1, 'Lot Rio Grande                                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(261, 1, 'Lot Sandra Regina                                                       ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(261, 2, 'Lot Sd Regina                                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(262, 1, 'Lot São Miguel                                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(262, 2, 'Lot S Miguel                                                            ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(263, 1, 'Lot São Pedro                                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(264, 1, 'Lot Vl Amorim                                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(267, 1, 'Vl dos Funcionários                                                     ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(268, 1, 'Lot Vila Nova                                                           ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(271, 1, 'Vl dos Sais                                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(271, 2, 'Vl dos Sas                                                              ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(272, 1, 'Vl dos Soldados                                                         ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(272, 2, 'Vl dos Sold                                                             ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(275, 1, 'Bairro do Natal                                                         ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(280, 1, 'Conjunto Urbis                                                          ');
INSERT INTO BDDNE.scDNE.tbBairroVariacao (nrBairro, nrVariacao, nmBairroVariacao) VALUES(281, 1, 'Jardim Panorama                                                         ');
