INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('11','Teatro',92,1,'2','2')
,('12','Dança',92,1,'2','2')
,('13','Circo',92,1,'2','2')
,('14','Ópera',92,1,'2','2')
,('15','Mímica',92,1,'2','2')
,('16','Ópera Rock',92,0,NULL,NULL)
,('17','Ações de capacitação e treinamento de pessoal',92,1,'2','2')
,('18','Teatro de formas animadas',92,1,'2','2')
,('19','Teatro de mamulengos',92,1,'2','2')
,('1A','Teatro de  bonecos e congêneres',92,1,'2','2')
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('1B','Desfile de  escola de samba',92,1,'2','2')
,('1C','Desfile de bloco carnavalesco',92,0,'2','2')
,('1D','Desfile de  cortejo da cultura popular ',92,1,'2','2')
,('1E','Construção de salas de teatro munic(< 100 mil hab)',92,1,'2','2')
,('1F','Construção de centros comunit.Munic(< 100 mil hab)',92,0,'2','2')
,('1G','Manutenção de salas de teatro Munic(< 100 mil hab)',92,0,'2','2')
,('1H','Manutenção de centros comunit.Munic(< 100 mil hab)',92,0,'2','2')
,('1I','Teatro musical',92,1,'2','2')
,('21','Jogos eletrônicos',160,1,'1','1')
,('22','Videofonográfica',160,0,NULL,NULL)
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('23','Produção Cinematográfica de curta metragem',160,0,'2','2')
,('24','Rádio/Tvs Educativa',160,0,NULL,NULL)
,('25','Multimídia',160,0,NULL,NULL)
,('26','Produção Cinematográfica de média metragem',160,0,'2','2')
,('27','Formação /Pesquisa/Informação',160,0,NULL,NULL)
,('28','Exibição Cinematográfica',160,0,'2','2')
,('29','Infra-estrutura Técnica Audiovisual',160,1,'1','1')
,('2A','Produção Videofonográfica de curta metragem',160,0,'2','2')
,('2B','Produção Videofonográfica de média metragem',160,0,'2','2')
,('2C','Formação Audiovisual',160,1,'2','2')
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('2D','Pesquisa Audiovisual',160,0,NULL,NULL)
,('2E','Doação de acervos audiovisuais',160,1,'2','2')
,('2F','Construção de salas de cinema (< 100 mil hab)',160,1,'2','2')
,('2G','Manutenção de salas de cinema (< 100 mil hab)',160,1,'2','2')
,('2H','Constr. centro comunitário c/sala cinema(<100 mil)',160,1,'2','2')
,('2I','Manut. centro comunitário c/sala cinema(<100 mil)',160,1,'2','2')
,('2J','Difusão de acervo audiovisual',160,0,'2','2')
,('2K','Preservação de acervos audiovisuais',160,1,'2','2')
,('2L','Restauração de acervos audiovisuais',160,1,'2','2')
,('2M','Produção de web série',160,1,'1','1')
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('2O','Rádios e TVs Educativas não comerciais',160,1,'2','2')
,('2P','Projetos Audiovisuais Transmidiáticos',160,1,'1','1')
,('2Q','Aquisi. equipamentos p/manut.-acervos audiovisuais',160,1,'2','2')
,('2R','Produção de conteúdo audiovisual de curta metragem',160,1,'2','2')
,('2S','Produção de conteúdo audiovisual de média metragem',160,1,'2','2')
,('2T','Difusão de acervo e conteúdo audiovisual',160,1,'2','2')
,('31','Música Popular Cantada',92,1,'1','1')
,('32','Música Erudita',92,1,'2','2')
,('33','Música Instrumental',92,1,'2','2')
,('34','Áreas Integradas',92,0,NULL,NULL)
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('35','Orquestra',92,0,NULL,NULL)
,('36','Doações de Acervos Musicais',92,0,NULL,NULL)
,('37','Canto Coral',92,1,'2','2')
,('38','Ações de capacitação e treinamento de pessoal',92,1,'2','2')
,('41','Plásticas',92,0,'1','1')
,('42','Gráficas',92,0,'1','1')
,('43','Filatelia',92,0,'1','1')
,('44','Gravura',92,0,'1','1')
,('45','Cartazes',92,0,'1','1')
,('46','Fotografia',92,1,'1','1')
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('47','Exposição Itinerante',92,0,'1','1')
,('48','Design',92,0,'1','1')
,('49','Artes Plásticas',92,1,'1','1')
,('4A','Artes Gráficas',92,0,'1','1')
,('4B','Exposição de Artes Visuais',92,1,'2','2')
,('4C','Moda',92,0,'1','1')
,('4D','Doações de Acervos de Artes Visuais',92,0,'1','1')
,('4E','Formação técnica e artística de profissionais',92,0,'1','1')
,('4F','Projeto educativo de artes visuais',92,0,'1','1')
,('4G','Projeto de fomento à cadeia produtiva arte visual',92,0,'1','1')
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('4H','Ações educativo-culturais',92,1,'2','2')
,('51','História',95,0,NULL,NULL)
,('52','Arquitetônico',91,0,NULL,NULL)
,('53','Arqueológico',91,0,NULL,NULL)
,('54','Museu',335,0,NULL,NULL)
,('55','Acervo',335,0,NULL,NULL)
,('56','Acervos Museológicos',335,0,NULL,NULL)
,('57','Cultura Afro Brasileira',94,0,NULL,NULL)
,('58','Cultura Indígena',92,0,NULL,NULL)
,('59','Artesanato/Folclore',92,0,NULL,NULL)
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('5A','Preservação de Patrimônio Imaterial',91,1,'2','2')
,('5B','Manutenção de equipamentos culturais em geral',92,1,'1','1')
,('5C','Ações de capacitação',91,0,'1',NULL)
,('5D','Doações / aquisições de acervos culturais em geral',91,1,'2','2')
,('5E','Preservação de Patrimônio Material',91,1,'2','2')
,('5F','Restauração de Patrimônio Material',91,1,'2','2')
,('5G','Preservação de Patrimônio Museológico',335,0,'2',NULL)
,('5H','Restauração de Patrimônio Museológico',335,0,'2',NULL)
,('5I','Preservação de Acervos',335,0,'2',NULL)
,('5J','Restauração de Acervos',335,0,'2',NULL)
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('5K','Preservação de Acervos Museológicos',335,0,'2',NULL)
,('5L','Restauração de Acervos Museológicos',335,0,'2',NULL)
,('5M','Gastronomia',92,1,'1','1')
,('5N','Aquisição de equipamentos p/ manutenção de acervos',335,0,'2',NULL)
,('5O','Manutenção de salas de Teatro (<100 mil hab)',92,0,'2',NULL)
,('5P','Manu centro comunitário c/sl teatro (<100 mil hab)',92,1,'2','2')
,('5Q','Construção de equipamentos culturais em geral',92,1,'1','1')
,('5R','Construção de salas de teatro munic(< 100 mil hab)',92,1,'2','2')
,('5S','Identificação, registro, educação do patrimônio',91,1,'2','2')
,('5T','Ações document./pesquisa/digitaliz./sistem.-acervo',91,1,'2','2')
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('5U','Preserv./revitaliz./edificações destinada-acervos',91,1,'2','2')
,('5V','Ações segurança p/preservação patrimônio/acervos',91,1,'2','2')
,('5W','Planos anuais de preservação do patrimônio/acervos',91,1,'2','2')
,('5X','Ações educativo-culturais',91,1,'2','2')
,('5Y','Treinamento  pessoal/aquis.equip. p/manut. Acervos',91,1,'2','2')
,('5Z','Elaboração de projetos de arquitetura e urbanismo',91,1,'2','2')
,('61','Edição de Livros',93,0,NULL,NULL)
,('62','Obras de Referência',93,1,'2','2')
,('63','História',95,0,NULL,NULL)
,('64','Filosofia',95,0,NULL,NULL)
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('65','Acervo Bibliográfico',93,1,'2','2')
,('66','Arquivo',95,0,NULL,NULL)
,('67','Biblioteca',93,0,NULL,NULL)
,('68','Evento Literário',93,1,'2','2')
,('69','Periódicos',93,0,NULL,NULL)
,('6A','Ações de formação e capacitação',92,0,'1','1')
,('6B','Eventos e ações de incentivo à leitura',93,1,'1','1')
,('6C','Livros  ou obras de referência - valor Artístico',93,1,'2','2')
,('6D','Livros  ou obras de referência - valor Literário',93,1,'2','2')
,('6E','Livros ou  obras de referência - valor Humanístico',93,1,'2','2')
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('6F','Periódicos e outras publicações',93,1,'1','1')
,('6G','Treina pessoal p manuten de acervos bibliográficos',93,1,'2','2')
,('6H','Aquisiç equip p/manuten de acervos bibliográficos',93,1,'2','2')
,('6I','Doação de acervos acessíveis ao público em geral',93,1,'2','2')
,('6J','Impressos/eletrônicos-artístico, literário, human.',93,0,'2','2')
,('6K','Aquis.acervos biblio.-artístico, literário, human.',93,0,'2','2')
,('6L','Aquisi. arquivísticos-artístico, literário, human.',93,1,'2','2')
,('6M','Manut. acervos biblio.artístico, literário, human.',93,1,'2','2')
,('6N','Manut. acervos arquiv.artístico, literário, human.',93,0,'2','2')
,('6O','Prese. acervos biblio.artístico, literário, human.',93,0,'2','2')
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('6P','Prese. acervos arquiv.artístico, literário, human.',93,0,'2','2')
,('6Q','Resta. acervos biblio.artístico, literário, human.',93,0,'2','2')
,('6R','Resta. acervos arquiv.artístico, literário, human.',93,0,'2','2')
,('6S','Treinamento-pessoal, demais ações de capacitação',93,1,'1','1')
,('6T','Aquis.equip. p/manut. acervos de bibliot. Públicas',93,1,'2','2')
,('6U','Aquisição equipamentos p/manut. acervos de museus',93,0,'2','2')
,('6V','Aquisição equip. p/manut. acervos arquivo públicos',93,0,'2','2')
,('6W','Aquisição equip. p/manut. acervos de cinematecas',93,0,'2','2')
,('6Y','Ações educativo-culturais',93,1,'2','2')
,('71','Artes Integradas',92,0,NULL,NULL)
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('72','Restauração/Bolsas',91,0,NULL,NULL)
,('73','Multimídia',160,0,NULL,NULL)
,('74','Carnaval',92,0,NULL,NULL)
,('75','Carnaval fora de época',92,0,NULL,NULL)
,('76','Cultura Popular',92,0,NULL,NULL)
,('77','Equipamentos culturais multifuncionais',92,0,NULL,NULL)
,('81','Produção Cinematográfica',160,0,NULL,NULL)
,('82','Produção de obras seriadas',160,0,'1','1')
,('83','Produção Televisiva',160,1,'2','2')
,('84','Produção Radiofônica',160,1,'2','2')
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('85','Distribuição Cinematográfica',160,0,NULL,NULL)
,('86','Preservação/Restauração da Memória Cinematográfica',160,0,NULL,NULL)
,('87','Difusão',160,0,NULL,NULL)
,('88','Formação/Pesquisa e informação',95,0,'1','1')
,('89','Intercâmbio cultural',93,0,NULL,NULL)
,('9A','Doação ou aquisição de acervos para museus',335,1,'2','2')
,('9B','Doação de acervos p/instit. preservação da memória',335,1,'2','2')
,('9C','Aquisição acervos p/instit. preservação da memória',335,1,'2','2')
,('9D','Preservação. Restauração, conservaçao, registro',335,1,'2','2')
,('9E','Identificação, registro e promoção',335,1,'2','2')
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('9F','Documentação e digitalização de acervos',335,1,'2','2')
,('9G','Sistemas de informações',335,1,'2','2')
,('9H','Ações de segurança para preservação de acervos',335,1,'2','2')
,('9I','Planos anuais de atividades e planos museológicos',335,1,'2','2')
,('9J','Exposições realizadas em museus',335,1,'2','2')
,('9K','Exposições organizadas com acervos de museus',335,1,'2','2')
,('9L','Exposições organizadas com museografia',335,1,'2','2')
,('9M','Pesquisa',335,1,'2','2')
,('9N','Ações educativs, seminários, congresso, palestras',335,1,'2','2')
,('9O','Criação projetos, construção, restauração, reforma',335,1,'2','2')
;
INSERT INTO SAC.dbo.Segmento (Codigo,Descricao,idOrgao,stEstado,tpEnquadramento,tp_enquadramento) VALUES 
('9P','Implan. projetos, construção, restauração, reforma',335,1,'2','2')
,('9Q','Espaços museais',335,1,'2','2')
,('9R','Treinamento de pessoal',335,1,'2','2')
,('9S','Aquisição de equipamentos p/preservação de acervos',335,1,'2','2')
,('9T','Aquisição de equipamentos p/manutenção de acervos',335,1,'2','2')
;