INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('A01','Projeto cultural cadastrado pelo sistema','C',0)
,('A02','Projeto cadastrado','C',1)
,('A03','Carta/Bolsa','C',0)
,('A04','Encaminhado p/Assessoria de Planenjamento','C',0)
,('A05','Pré Análise - Avaliação em 2001','C',0)
,('A06','Desclassificado/Não Enquadramento nos Objetivos','C',0)
,('A07','Encaminhado p/Comissão de Avaliação','C',0)
,('A09','Projeto não selecionado','C',1)
,('A10','Pré Análise','C',1)
,('A11','Diligência  Documental','C',1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('A12','Aguarda complementação de documentos','C',1)
,('A13','Arquivado - solicitação de desistência do proponente','C',1)
,('A14','Indeferido - não enquadramento nos objetivos e fins da Lei 8313/91 ou do Decreto 5761/06','C',1)
,('A16','Indeferido - Projeto já realizado.','C',1)
,('A17','Indeferido - não atendimento à diligência','C',1)
,('A18','Arquivado/Insuficiência de recursos','C',0)
,('A19','Enviado para o mecenato','C',0)
,('A20','Indeferido - projeto em duplicidade','C',1)
,('A21','Carta de arquivamento','C',0)
,('A22','Aguardando cadastro de proponente/Teto de valores','C',0)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('A23','Indeferido - somatório dos projetos apresentados excede o limite permitiddo para pessoa física',NULL,1)
,('A24','Indeferido - somatório dos projetos apresentados excede o limite permitiddo para pessoa jurídica',NULL,1)
,('A25','Alteração de valor','C',0)
,('A26','Arquivado/Não enquadramento no âmbito da SMAC','C',0)
,('A27','Carta circular/Contextualização do projeto','C',0)
,('A28','Projeto priorizado',NULL,0)
,('A29','Análise para enquadramento',NULL,0)
,('A30','Análise do plano de trabalho',NULL,0)
,('A31','Corrigindo plano de trabalho',NULL,0)
,('A32','Aguardando correção do plano de trabalho',NULL,0)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('A33','Análise do projeto técnico',NULL,0)
,('A34','Aguardando correção do projeto técnico',NULL,0)
,('A35','Aguardando complementação do projeto',NULL,0)
,('A36','Aguardando definição da SPMAP',NULL,0)
,('A37','Aguarda Análise/Redimensionamento','C',0)
,('A38','Aguarda Portaria/Redimensionamento','C',0)
,('A39','Encaminhado para consultoria jurídica',NULL,0)
,('A40','Arquivado/Projeto acima do teto adotado pela CNIC','C',0)
,('A41','Indeferido - 50% de corte valor solicitado','C',1)
,('A42','Projeto arquivado - não atendimento à diligência técnica',NULL,1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('B01','Proposta transformada em projeto','C',1)
,('B02','Projeto enquadrado','C',1)
,('B03','Projeto enquadrado com recurso','C',1)
,('B04','Projeto em avaliação documental','C',1)
,('B05','Reanalisar enquadramento','C',1)
,('B10','Despacho para análise técnica','C',0)
,('B11','Encaminhado para análise técnica','C',1)
,('B12','Aguarda parecer técnico','C',1)
,('B13','Prazo de análise técnica vencido','C',0)
,('B14','Diligenciado - Parecer técnico','C',1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('B15','Encaminhado para emissão das passagens','C',1)
,('B16','Aguarda adequação do projeto',NULL,0)
,('B20','Projeto adequado à realidade de execução','C',1)
,('C07','Projeto selecionado para atendimento',NULL,1)
,('C08','Análise técnica concluída','R',1)
,('C09','Projeto fora da pauta - Proponente Inabilitado',NULL,1)
,('C10','Projeto incluído em pauta para avaliação da CNIC','R',1)
,('C11','Projeto incluído em pauta extraordinária da CNIC','R',0)
,('C12','Análise Técnica - FNC','R',1)
,('C13','Projeto incluído na pauta de complementação para avaliação da CNIC','R',1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('C14','Projeto incluído na pauta de prorrogação da CNIC','R',0)
,('C15','Parecer Desfavorável',NULL,0)
,('C16','Parecer Favorável','R',1)
,('C17','Pauta não prioridade','R',0)
,('C18','Pauta ad refendum','R',0)
,('C19','Banda selecionada para atendimento',NULL,0)
,('C20','Parecer técnico emitido','R',1)
,('C21','Projeto incluído na pauta de redução da CNIC','R',1)
,('C22','Projeto incluído na pauta de recurso','R',1)
,('C23','Pauta FNC/Processo seletivo','R',1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('C24','Extra Pauta do FNC','R',1)
,('C25','Parecer Técnico desfavorável','R',1)
,('C26','Projeto incluído na pauta da CNIC para reanálise/análise complementar',NULL,1)
,('C30','Diligenciado - Comissão Nacional de Incentivo à Cultura - CNIC',NULL,1)
,('D01','Projeto aprovado e aguardando ajuste sugerido pela plenária',NULL,1)
,('D02','Readequação do projeto aprovada. Aguardando análise documental',NULL,1)
,('D03','Projeto aprovado - aguardando análise documental',NULL,1)
,('D04','Retornou da  CNIC/Em análise','A',0)
,('D05','Em tramites de aprovação',NULL,0)
,('D06','Encaminhado para CEC/portaria complementação',NULL,0)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('D07','Encaminhado para CEC/portaria prorrogação',NULL,0)
,('D08','Carta de aprovação p/1998',NULL,0)
,('D09','Aguardando publicação de portaria','P',1)
,('D10','Aguarda Portaria II','P',1)
,('D11','Projeto aprovado - Proponente inabilitado','A',1)
,('D12','Retirado de Pauta pela CNIC',NULL,1)
,('D13','Vistas',NULL,0)
,('D14','Indeferido',NULL,1)
,('D15','Aguarda Portaria III','P',0)
,('D16','Aguarda Portaria de Complementação','P',1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('D17','Aguardando publicação de portaria de Prorrogação','P',1)
,('D18','Projeto não selecionado - FNC',NULL,0)
,('D19','Projeto Selecionado p/atendimento - FNC','A',1)
,('D20','Recurso',NULL,1)
,('D21','Aguarda Portaria VI','P',0)
,('D22','Aguardando elaboração de portaria de Prorrogação',NULL,1)
,('D23','Aguarda portaria de redução','P',1)
,('D24','Projeto em análise documental para publicação de portaria de captação','A',1)
,('D25','Diligenciado - Projeto aprovado - (Solicitação de Documentos)','A',1)
,('D26','Pedido de Prorrogação Excepcional','A',0)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('D27','Encaminhado para inclusão em portaria','A',1)
,('D28','Encaminhado p/inclusão em portaria/complementação','A',1)
,('D29','Encaminhado p/inclusão em portaria/redução.','A',1)
,('D30','Banda Selecionada',NULL,0)
,('D31','Aprovação suspensa','A',1)
,('D32','Complementação aprovada - proponente inabilitado','A',1)
,('D33','Diligenciado - Readequação - Análise Técnica','A',1)
,('D34','Complementação aprovada - proponente habilitado','A',1)
,('D35','Redução aprovada - proponente habilitado.','A',1)
,('D36','Aprovado condicionado a apresentação de documentação','A',0)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('D37','Termo de Compromisso OK - Aguardando Certidões','A',0)
,('D38','CADIN - Inadimplente',NULL,1)
,('D40','Análise de recurso prestação de contas','X',1)
,('D41','Diligenciado - Análise de Recurso',NULL,1)
,('D50','Projeto apreciado pela Comissão Nacional de Incentivo à Cultura - CNIC',NULL,1)
,('D51','Projeto apreciado pela CNIC - Aguardando superação/desistência do prazo recursal',NULL,1)
,('D52','Projeto encaminhado para homologação',NULL,1)
,('D53','Encaminhado para inclusão em portaria de avaliação de resultado',NULL,1)
,('D54','Aguardando publicação de portaria de Avaliação de Resultado',NULL,1)
,('D60','Projeto enquadrado na exceção de execução imediata',NULL,1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('E00','Aguarda Complementação',NULL,0)
,('E01','Encaminhado p/Coordenadoria de Convênios',NULL,0)
,('E02','Projetos Especiais Contemplado',NULL,0)
,('E03','Avaliação p/ o próximo ano',NULL,0)
,('E04','Arquivado - Art 14 Decreto Lei 200','X',0)
,('E05','Análise Financeira do Relatório Final - P.C.','X',0)
,('E06','Recibo cancelado - captação não efetivada',' ',0)
,('E07','Projeto aprovado aguardando registro na CVM',NULL,0)
,('E08','Autorizada captação p/o próximo exercício',NULL,0)
,('E09','Projeto Cancelado',NULL,2)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('E10','Autorizada a captação total dos recursos','E',1)
,('E11','Expirado o prazo de captação total',NULL,1)
,('E12','Autorizada a captação residual dos recursos','E',1)
,('E13','Projeto em execução - Encerrado prazo de captação','X',1)
,('E14','Aguarda Decisão Superior','X',1)
,('E15','Expirado o prazo de captação parcial','X',1)
,('E16','Projeto encerrado por excesso de prazo sem captação ','X',1)
,('E17','Diligenciado - Prestação de Contas','X',1)
,('E18','Avaliação Técnica do Relatório Final - P.C.','X',1)
,('E19','Prestação de Contas Aprovada','X',1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('E20','Inadimplente - não respondeu a diligência da Prestação de Contas','X',1)
,('E21','Inadimplência Suspensa - Mecenato','X',0)
,('E22','Instaurada Tomada de Contas Especial','X',1)
,('E23','Inadimplente','X',1)
,('E24','Apresentou prestação de contas','X',1)
,('E25','Análise de resposta de diligência - Objeto','X',1)
,('E26','Emissão de Carta 02',NULL,0)
,('E27','Análise Financeira da Prestação de Contas','X',1)
,('E28','Pauta de Complementação',NULL,0)
,('E29','Pauta de Prorrogação',NULL,0)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('E30','Análise de resposta de diligência',NULL,1)
,('E31','Aguarda Parecer/Complementação',NULL,0)
,('E32','Cancelamento Solicitado',NULL,0)
,('E33','Prorrogação Negada',NULL,0)
,('E34','Prestação de contas encaminhada para UNB',NULL,0)
,('E35','Prestação de contas encaminhada p/SPOA - Consultor',NULL,0)
,('E36','Arquivado por ter 24 meses aprovação sem captação de recursos',NULL,1)
,('E37','Diligenciado PC - UNB','X',0)
,('E38','Inadimplente - Diligência na PC - UNB','X',0)
,('E39','Diligênciado UNB - Relatório Final I','X',0)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('E40','Diligênciado UNB - Relatório Final II','X',0)
,('E41','Resposta diligência relatório final - UNB','X',0)
,('E42','Relatorio Recebido - UNB','X',0)
,('E43','Relatorio Aprovado - UNB','X',0)
,('E44','Aguarda Registro de CPB','X',0)
,('E45','Apresentou prestação de contas parcial','X',1)
,('E46','Emisão do parecer final da Prestação Contas','X',1)
,('E47','Projeto arquivado - recursos transferidos FUNARTE','X',0)
,('E48','Recurso não liberado - Execução encerrada',NULL,2)
,('E49','Projeto Arquivado - Recursos transferidos','E',2)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('E50','Diligenciado - movimentação da conta corrente',NULL,1)
,('E51','Diligência na prorrogação/P.C. parcial',NULL,0)
,('E52','Analisando prorrogação/P.C. parcial',NULL,0)
,('E53','Banda sob Acompanhamento',NULL,0)
,('E54','Banda Advertida',NULL,0)
,('E55','Banda em Funcionamento',NULL,0)
,('E56','Banda em Débito com o Acompanhamento',NULL,0)
,('E57','Banda em Formação',NULL,0)
,('E58','Banda Contemplada',NULL,0)
,('E59','Diligenciado - Readequação','A',1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('E60','Diligenciado - fiscalização',NULL,1)
,('E61','Diligenciado - na avaliação do relatório trimestral',NULL,1)
,('E62','Diligenciado - na avaliação do relatório cumprimento de objeto',NULL,1)
,('E63','Projeto arquivado - por excesso de prazo sem captação',NULL,1)
,('E64','Projeto arquivado - captação/execução encerradas',NULL,1)
,('E65','Projeto arquivado - solicitação de arquivamento, de projeto de incentivo fiscal, feito pelo proponente',NULL,1)
,('E66','Inadimplente - por não responder diligência na avaliação do relatório cumprimento de objeto',NULL,1)
,('E67','Indicação para tomada de contas especial',NULL,1)
,('E68','Aguarda análise financeira',NULL,1)
,('E69','Inadimplente - por não responder a diligência de fiscalização',NULL,1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('E70','Relatório final enviado ao MinC',NULL,1)
,('E71','Inadimplente - por não responder diligência solicitando o envio do relatório trimestral',NULL,1)
,('E72','Execução Suspensa de Forma Cautelar',NULL,1)
,('E73','TCE julgada pelo TCU','X',1)
,('E74','Prazo prorrogado para a inserção da prestação de contas no sistema',NULL,1)
,('E75','Expirado o prazo de execução do projeto',NULL,1)
,('E76','Encaminhado para inclusão em portaria - Prestação de Contas',NULL,1)
,('E77','Aguarda laudo final',NULL,1)
,('E78','Débito inferior ao valor mínimo para TCE','X',1)
,('E79','Projeto não executado por insuficiência de captação de recursos',NULL,1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('E80','Inadimplente - Proponente notificado a apresentar prestação de contas',NULL,1)
,('E81','Inadimplente - Não atendeu a notificação para apresentar prestação de contas',NULL,1)
,('E90','Projeto liberado para adequação à realidade de execução','c',1)
,('E91','Aguarda revisão financeira',NULL,1)
,('E92','Aguarda revisão de resultados',NULL,1)
,('E93','Aguarda revisão da diretoria',NULL,1)
,('E94','Aguarda decisão da secretaria',NULL,1)
,('E95','Aguarda revisão técnica',NULL,1)
,('E96','Em análise técnica',NULL,1)
,('F00','Projeto prorrogado',' ',0)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('G01','Aguarda descontingenciar orçamento/limite Financ.','F',1)
,('G02','Destaque em vigência',NULL,1)
,('G03','Análise Documental','F',1)
,('G04','Diligênciado/Documento/PT','F',1)
,('G05','Encaminhado p/Consultoria Juridica','F',1)
,('G06','Análise de regularidade',NULL,0)
,('G07','Projetos em Duplicidade',NULL,0)
,('G08','Visto da Consultoria Juridica','F',1)
,('G09','Em Andamento','F',0)
,('G10','Empenhado','F',1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('G11','Projeto Conveniado','F',1)
,('G12','Aguarda exigência da consultoria jurídica',NULL,1)
,('G13','Enviado p/Pagamento','F',1)
,('G14','Convênio em vigência','F',1)
,('G15','Encerrado o prazo de vigência do convênio','F',1)
,('G16','Arquivado/Não cumprimento de diligência',NULL,1)
,('G17','Solicitação de arquivamento feito pelo proponente',NULL,1)
,('G18','Diligência na prestação de contas do convênio','F',1)
,('G19','Prestação de contas de convênio aprovada','F',1)
,('G20','Inadimplente - não respondeu a diligência da Prestação de Contas (FNC)','F',1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('G21','Análise Técnica do Relatório Final P.C. - convênio','F',1)
,('G22','Analisando prestação de contas - convênio','F',1)
,('G23','Convênio irregular - Conveniado inadimplente','F',1)
,('G24','Apresentou prestação de contas de convênio','F',1)
,('G25','Projeto arquivado/decurso de prazo',NULL,0)
,('G26','Projeto arquivado/não atendimento documental',NULL,0)
,('G27','Convênio cancelado',NULL,0)
,('G28','Encerrado a vigência - projeto em execução','F',1)
,('G29','Arquivado/Não enquadrado nas prioridades do FNC',NULL,0)
,('G30','Arquivado/Insuficiência de recursos',NULL,0)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('G31','Prestação de contas encaminhada p/SAA - Convênios',NULL,1)
,('G32','Para CJ após atendimento da exigência',NULL,1)
,('G33','Inadimplência Suspensa - Convênio','F',1)
,('G34','Para assinatura do convênio pelo dirigente',NULL,1)
,('G35','Enviado para publicação de extrato de convênio',NULL,1)
,('G36','Projeto  aceito no edital',NULL,1)
,('G37','Projeto de edital - encaminhado para avaliação',NULL,1)
,('G38','Para CAAP atender exigência DCC',NULL,0)
,('G39','Em devolução a CCON',NULL,0)
,('G40','Aguardando definição do proponente',NULL,1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('G41','Para empenho',NULL,1)
,('G42','Projeto premiado',NULL,1)
,('G43','Aguarda análise técnico/financeira',NULL,1)
,('G44','Descentralização de recursos - em vigência','F',1)
,('G45','Descentralização de recursos - prestação de contas','F',1)
,('G46','Descentralização de recursos - encerrada','F',2)
,('G47','Em processo de instauração de Tomada de Contas Especial','F',1)
,('G48','Vistoria in loco','F',1)
,('G49','Encaminhado para assinatura do Secretário',NULL,1)
,('G50','Assinado pelo Secretário, para continuidade das providências',NULL,1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('G51','Edital - Encaminhado a Comissão de Avaliação',NULL,1)
,('G52','Edital - Avaliado pela Comissão',NULL,1)
,('G53','Solicitado Prestação de Contas de Convênio/Diligência',NULL,1)
,('G54','Análise de resposta de diligência - FNC',NULL,1)
,('G55','Edital - Encaminhado para análise da Coordenação',NULL,1)
,('G56','Projeto arquivado - solicitação de arquivamento, de projeto de Edital/FNC, feita pelo proponente',NULL,1)
,('H01','Emitir ofício de notificação',NULL,0)
,('H04','Proponente inadimplente',NULL,1)
,('H06','Solicitar complement. documentos /esclarecimentos',NULL,0)
,('K00','Projeto Arquivado',NULL,1)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('K01','Arquivado por excesso de projetos apresentados',NULL,1)
,('K02','Arquivado por incapacidade técnica do proponente',NULL,0)
,('K03','Bolsa concluída/Relatório final aprovado',NULL,0)
,('K04','Bolsa Virtuose/Arquivado/Análise Documental',NULL,0)
,('K05','Bolsa Virtuose/Arquivado/Análise do Mérito',NULL,0)
,('K06','Bolsa Virtuose/Prorrogação Aprovada',NULL,0)
,('K07','Bolsa Virtuose/Prorrogação Negada',NULL,0)
,('K10','Encaminhado para a ANCINE',NULL,0)
,('L01','Prestação de contas aprovada com certificação de qualidade-gestão','L',0)
,('L02','Prestação de contas aprovada sem certificação de qualidade-gestão','L',0)
;
INSERT INTO SAC.dbo.Situacao (Codigo,Descricao,AreaAtuacao,StatusProjeto) VALUES 
('L03','Prestação de contas aprovada com ressalva formal e sem prejuízo','L',1)
,('L04','Prestação de contas aprovada com ressalva material ou prejuízo','L',0)
,('L05','Prestação de contas desaprovada com notificação de cobrança','L',1)
,('L06','Prestação de contas desaprovada com INDICATIVO para Tomada de Contas Especial','L',1)
,('L07','Recolhimento integral dos recursos','L',2)
,('L08','Prestação de contas aprovada após ressarcimento ao erário.','X',1)
,('L09','Débito Parcelado','X',1)
,('L10','Prestação de contas reprovada - Inabilitação Prescrita','L',1)
,('L11','Prestação de contas reprovada ? Inabilitação suspensa','L',1)
;