INSERT INTO sac.dbo.Produto (Codigo,Descricao,Area,Sintese,Idorgao,stEstado) VALUES
(1,'Livro','0','Produção e edição; doação ou comercialização.',93,0)
,(2,'Seminário / Simpósio / Encontro / Congresso / Palestra','0','Reunião de artista ou profissional da área cultural.',92,0)
,(3,'Curso / Oficina / Estágio','0','Atividade de aperfeiçoamento profissional.',92,0)
,(4,'Concurso','0','Concurso de fomento a atividade cultural.',92,0)
,(5,'Prêmio','0','Prêmio de incentivo a atividade cultural.',95,0)
,(6,'Monografia/Ensaio','0','Estudo ou ensaio publicado ou não.',95,0)
,(7,'Intercâmbio','0','Passagem concedida para fins de difusão e/ou intercâmbio.',92,0)
,(8,'Bolsa','0','Artista e/ou profissional beneficiado por concessão de bolsa.',92,0)
,(10,'CD-Rom','0','Produção e edição; doação ou comercialização.',160,1)
,(11,'Vídeo','0','Produção e edição; doação ou comercialização.',160,0)
;
INSERT INTO sac.dbo.Produto (Codigo,Descricao,Area,Sintese,Idorgao,stEstado) VALUES
(12,'DVD','0','Produção e edição; doação ou comercialização.',92,0)
,(13,'Patrimônio/Memória','0','Bem cultural preservado, restaurado ou adquirido.',219,1)
,(14,'Bem Imóvel Construído','0','Construção de imóveis destinados a atividades culturais.',219,1)
,(15,'Arte-Educação','0','Ação de cunho cultural e educativo.',92,1)
,(16,'Catálogo','0','Produção e edição de catálogo vinculado a exposição, festival, mostra e outros eventos culturais.',92,0)
,(17,'Pesquisa','0','Produção de pesquisa de atividade cultural.',95,0)
,(18,'Festival/Mostra','0','Apoio a festival na área cultural.',92,0)
,(19,'Espetáculo de Artes Cênicas','1','Espetáculos de teatro, circo, dança, mímica.',92,0)
,(20,'Texto Teatral','1','Criação de texto teatral.',92,0)
,(21,'Montagem','1','Produção de espetáculos de teatro, dança, ópera, circo. Seguido de temporada.',219,1)
;
INSERT INTO sac.dbo.Produto (Codigo,Descricao,Area,Sintese,Idorgao,stEstado) VALUES
(22,'Circulação','1','Circulação de espetáculos de teatro, dança, ópera, circo por diferentes localidades.',219,1)
,(23,'Ópera (Composição)','1','Criação de ópera, compreendendo a composição musical e o libreto.',92,0)
,(24,'Mostra de Artes Cênicas','1','Mostra de teatro, dança, ópera ou circo.',219,1)
,(25,'Equipamentos para Espaços de Artes Cênicas','1','Aquisição de equipamentos para espaços de artes cênicas.',92,0)
,(26,'Longa-metragem','2','Produção e comercialização de longas metragens, independentemente do suporte ou gênero.',160,1)
,(27,'Média-metragem','2','Produção de médias metragens, independentemente do suporte ou gênero.',160,0)
,(28,'Filme','2','Produção de curtas metragens, independentemente do suporte ou gênero.',93,1)
,(29,'Concurso de Longa Metragem','2','Fomento de longas metragens, independentemente do gênero.',219,1)
,(30,'Concurso de Média Metragem','2','Fomento de médias metragens, independentemente do gênero.',219,1)
,(31,'Concurso de Curta Metragem','2','Fomento de curtas metragens, independentemente do gênero.',219,1)
;
INSERT INTO sac.dbo.Produto (Codigo,Descricao,Area,Sintese,Idorgao,stEstado) VALUES
(32,'Concurso de Roteiro','2','Fomento de Roteiro.',219,1)
,(33,'Concurso de Desenvolvimento de Projeto','2','Fomento a Desenvolvimento de Projetos.',219,1)
,(34,'Concurso de Telefilmes','2','Registra os concursos de Telefilmes.',219,1)
,(36,'Modernização de Museu / Espaço Cultural','5','Modernização de museus ou espaços dedicados à memória cultural.',91,0)
,(37,'Orquestra - Manutenção','3','Projeto apoiados no Programa de Apoio a Orquestra.',92,0)
,(38,'Preservação  de Acervo Cultural','5','Conjunto de bens adquirido, preservado ou tratado técnicamente.',91,0)
,(39,'Bem Imaterial - Registro','5','Registro de bem cultural de natureza imaterial.',91,0)
,(40,'Projeto de Intervenção no Patrimônio Cultural','5','Projeto elaborado para intervenção de bem cultural protegido.',219,1)
,(47,'Roteiro de Audiovisual','2','Produção de roteiros.',160,1)
,(48,'Desenvolvimento de Projeto','2','Apoio à Desenvolvimento de Projetos.',219,1)
;
INSERT INTO sac.dbo.Produto (Codigo,Descricao,Area,Sintese,Idorgao,stEstado) VALUES
(49,'Equipamento Audiovisual Adquirido / Doado','2','Doação ou aquisição de equipamentos para a produção audiovisual.',160,0)
,(50,'Sítio de Internet','0','Criação e/ou desenvolvimento de redes virtuais.',160,0)
,(51,'Apresentação Musical','3','Espetáculos de música popular e eruditas.',92,0)
,(52,'CD-Áudio ou outro suporte para música','0','Produção e edição; doação ou comercialização.',92,0)
,(53,'Obra Musical Composta','3','Composições encomendadas.',92,1)
,(54,'Partitura - Edição','3','Edição de partituras.',92,0)
,(55,'Partitura-Distribuição','3','Distribuíção de partituras.',92,1)
,(56,'Instrumento Musical - Aquisição','3','Instrumentos musicais adquiridos para grupos musicais, orquestras sinfônicas e outros conjuntos.',92,0)
,(57,'Mostra Musical','3','Mostras musicais de todos os gênero.',219,1)
,(58,'Kit de Instrumentos de Bandas de Música Doado','3','Doação de conjuntos de instrumentos de sopro através do Programa Nacional Bandas de Música.',219,1)
;
INSERT INTO sac.dbo.Produto (Codigo,Descricao,Area,Sintese,Idorgao,stEstado) VALUES
(59,'Banco de Dados','3','Disponibilização via rede de computadores de um conjunto de partituras, de monografias, discografias ou estudos ou outros dados sobre música.',160,0)
,(60,'Manutenção / Equipamentos para Grupo Musical / Escola de Música','3','Manutenção, aquisição de equipamentos e instrumentos musicais para grupos musicais ou escolas de música.',219,1)
,(61,'Grupo Musical - Formação','3','Criação de um novo grupo musical.',219,1)
,(62,'Exposição de Artes','0','Produção e circulação de exposições de artes e bens culturais',92,0)
,(63,'Bem material - Tombamento','5','Tombamento de bem cultural.',91,1)
,(64,'Autorizações','5','Para pesquisa arqueológica, movimentação de obra de arte e intervenção física em bem cultural.',219,1)
,(65,'Sistema de Informação','5','Cadastro e banco de dados com informações sobre o patrimônio de bens culturais e sua gestão.',219,1)
,(66,'Evento Realizado','5','Divulgação e promoção do patrimônio histórico, artístico e arqueológico nacional.',219,1)
,(67,'Bem Móvel - Restauração / Preservação / Aquisição','0','Preservação, restauração e aquisição de bem móvel de interesse cultural.',91,0)
,(68,'Bem Imóvel - Reforma / Ampliação / Construção / Aquisição','0','Reforma e/ou ampliação, construção ou aquisição.',91,0)
;
INSERT INTO sac.dbo.Produto (Codigo,Descricao,Area,Sintese,Idorgao,stEstado) VALUES
(69,'Bem Imóvel - Restauração / Preservação','0','Preservação e restauração de bem imóvel ou elemento artístico.',91,0)
,(70,'Sítio Histórico -  Restauração / Preservação','5','Preservação e/ou restauração de conjunto de bens em sítio de interesse histórico e/ou cultural.',91,0)
,(71,'Material Impresso  Distribuído','5','Distribuíção de material impresso, informativo e promocional referente ao patrimônio cultural.',219,1)
,(72,'Catalogação','0','Catalogação de bens culturais.',219,1)
,(73,'Inventário de Patrimônio Material','5','Identificação, classificação e/ou invetário de bem cultural.',91,0)
,(74,'Inventário de Patrimônio Imaterial','5','Mapeamento, identificação, catalogação e inventário do patrimônio cultural imaterial.',91,0)
,(75,'Cultura Popular','0','Arte e tradição popular.',219,1)
,(79,'Bem Móvel Cultural Adquirido/Doado','5','Aquisição ou doação de bem móvel de interesse cultural.',219,1)
,(80,'Biblioteca','6','Registra as ações do Programa Uma Biblioteca em Cada Município e, também, a implantação de biblioteca via Mecenato.',93,0)
,(81,'Acervo  Bibliográfico e Documental','6','Acervo bibliográfico restaurado, preservado, adquirido ou doação de kits (Revitalização de Bibliotecas).',93,0)
;
INSERT INTO sac.dbo.Produto (Codigo,Descricao,Area,Sintese,Idorgao,stEstado) VALUES
(82,'Biblioteca Virtual','6','Criação e/ou desenvolvimento de redes virtuais.',93,0)
,(83,'Equipamentos para Biblioteca','6','Doação de livros ou aquisição de equipamentos.',93,0)
,(84,'Feira de Livros','6','Apoio ao evento caracterizados como tal.',93,0)
,(85,'Periódico','6','Produção e edição.',93,0)
,(86,'Bem Notificado / Embargado / Vistoriado','5','Bens protegidos pela União integrantes do patrimônio cultural e as eventuais notificações e embargos decorrentes.',219,1)
,(87,'Modernização e Equipagem de Museus e Espaços Culturais','0','Projeto que visa modernizar e equipar museu e espaço cultural.',91,0)
,(89,'Mostra Audiovisual','2','Mostra de Audioviusal, independentemente do gênero ou suporte.',160,1)
,(91,'Série','2','Produção e comercialização de séries, independentemente do gênero ou do suporte.',160,1)
,(92,'Programa Radiofônico','2','Produção e comercialização de programas radiofônico, independentemente do gênero.',160,0)
,(93,'Obra Exibida','2','Exibição de obras audiovisuais, independentemente do gênero, da metragem ou do suporte.',160,0)
;
INSERT INTO sac.dbo.Produto (Codigo,Descricao,Area,Sintese,Idorgao,stEstado) VALUES
(94,'Obra Distribuída','2','Lançamento e/ou distribuição de obras audiovisuais, independentemente do gênero, metragem ou suporte.',160,1)
,(95,'Apoio/Lançamento de Evento','7','Apoio e /ou participação em eventos de outros órgãos/instituições.',219,1)
,(96,'Bem Imóvel Revitalizado','7','Bem de relevância histórica e /ou cultural negra revitalizado.',219,1)
,(97,'Cartilha Publicada','7','Cartilha/caderno informativo.',219,1)
,(98,'Centro de Referência','7','Obra arquitetôncia referente ao Centro Nacional de Informações e Referência da Cultura Negra.',219,1)
,(99,'Curso Profissionalizante','7','Curso de formação profissional para produção negra, geralmente quilombolas.',219,1)
,(100,'Fotografia - Aquisição / Exposição / Pesquisa','7','Aquisição e apoio à pesquisa e registro fotográfico.',92,0)
,(101,'Reconhecimento de Território Cultural Afro-brasileiro','7','Reconhecimento, publicado em D.O.U. de terrritórios culturais afro-brasileiros, como: Terreiros, Sítios Históricos, Terra de Remanescentes, Igreja, Praças etc.',219,1)
,(102,'Acervo Cultural Preservado','7','Acervos culturais preservados ou tratados tecnicamente.',219,1)
,(103,'Titulação de Terras Remanescentes de Quilombos','7','Entrega do Título de posse de terra á comunidade quilombola.',219,1)
;
INSERT INTO sac.dbo.Produto (Codigo,Descricao,Area,Sintese,Idorgao,stEstado) VALUES
(104,'Usuário Atendido','8','Registra o número de pesquisadores/leitores que frequentam o órgão.',219,1)
,(105,'Souvenirs','8','Registra peças promocionais da marca do órgão.',219,1)
,(106,'Bolsa Concedida','8','Registra as bolsas concedidas aos autores brasileiros e editores estrangeiros para tradução de livros brasileiros.',219,1)
,(107,'Direito Autoral Registrado','8','Garantir os direitos do autor que lhe são conexos, estabelecidos em lei.',219,1)
,(108,'ISBN Atribuído a Livro','8','Registro sistemático de todas as obras editadas no Brasil.',219,1)
,(109,'Publicação não periódicas','0','Publicação de carater informativo sem periocidade.',400,1)
,(110,'Inspeção Técnica e Fiscalização de Bens Culturais','9','Inspeção/Fiscalização de bens protegidos pela União integrantes do patrimônio cultural e as eventuais notificações e embargos decorrentes.',219,1)
,(111,'Parecer Técnico','9','Parecer para intervenção de bem cultural protegido.',219,1)
,(112,'Bem imaterial - tombamento','5','Bem imaterial da cultura brasileira',91,1)
,(113,'Festa Popular',' ','Festa incluída no calendário local.',92,0)
;
INSERT INTO sac.dbo.Produto (Codigo,Descricao,Area,Sintese,Idorgao,stEstado) VALUES
(114,'Desfile de Carnaval',' ','Desfile de agremeação carnavalesca em desfiles oficiais das associações.',92,0)
,(115,'Curta Metragem (até 15'')',' ','Obra cinematográfica de até 15''.',160,0)
,(116,'Oficina',' ','Desenvolvimento de capacitação de agentes culturais por meio de exercícios práticos.',92,1)
,(117,'Companhia Teatral  - MANUTENÇÃO',' ','Manutenção de companhia permanente de teatro.',92,0)
,(118,'Aquisição de Acervo Museológico',' ','Aquisição de obras para composição de acervo permanente de Museus.',91,0)
,(119,'Cartilha',' ','Publicação pedagógica auxliar a outro produto ou serviço cultural.',92,0)
,(120,'Preservação/Restauração de acervo audiovisual',' ','Preservação/Restauração de acervo audiovisual - Recuperação de acervos.',160,0)
,(121,'Oficina /Workshop/Seminário Audiovisual',' ','Oficina /Workshop/Seminário Audiovisual',160,0)
,(122,'Programa de Televisão ',' ','Programa de Televisão ',160,0)
,(123,'Filme de animação',' ','Filme de animação',160,0)
;
INSERT INTO sac.dbo.Produto (Codigo,Descricao,Area,Sintese,Idorgao,stEstado) VALUES
(124,'Festival/Mostra - Audiovisual',' ','Festival/Mostra audiovisual',160,0)
,(125,'Manutenção de escola de arte',' ','Manutenção de escola de arte',92,0)
,(126,'Manutenção de espaço de artes cênicas',' ','Manutenção de teatros e centros culturais para o desenvolvimento de artes cênicas.',92,0)
,(127,'Plano Anual',' ','Plano Anual',92,0)
,(130,'Bolsa de Pesquisa',' ','Concessão de bolsas para desenvolvimento de pesquisa nas áreas das ciências humanas e sociais',95,0)
,(131,'Construção de sala de Cinema',' ','Construção de cinema.',91,0)
,(132,'Manutenção de Instituição Cultural',' ','Manutenção de instituição cultural com caráter permanente.',92,0)
,(133,'Manutenção de Escola de Dança',' ','Manutenção de atividades didáticas de escola, da área de dança.',92,0)
,(134,'Manutenção de Museu',' ','Manutenção de espaço museológico com realização de ações permanentes como presevação de acervo.',335,0)
,(150,'Companhia de Dança - Manutenção',' ','Manutenção de companhias de dança permanentes.',92,0)
;
INSERT INTO sac.dbo.Produto (Codigo,Descricao,Area,Sintese,Idorgao,stEstado) VALUES
(151,'Audiodescrição','0','é o recurso que permite a inclusão de pessoas com deficiência visual, baixa visão e deficiência cognitiva em cinema, teatro, ópera, espetáculos em geral, seminários, congressos, DVDs e programas de TV.',160,1)
,(152,'Formação de Plateia','0','Ações presenciais e gratuitas, destinadas a alunos de instituições de ensino de qualquer nível, que visem a conscientização para a importância da arte e da cultura por intermédio do produto do projeto cultural.',92,1)
,(153,'Jogo eletrônico','0','trata-se de uma obra audiovisual interativa cujas imagens são alteradas em tempo real a partir de ação do (s) jogador (es).',160,0)
,(154,'Aplicativo','2','é um software desenvolvido para ser instalado em um dispositivo (móvel ou não) para processar dados eletronicamente, com objetivos diversos',160,0)
,(155,'Websérie','2','é uma série de episódios lançados na internet e faz parte de um novo meio de broadcasting chamado de web televisão.',160,0)
,(156,'Contrapartidas Sociais','0',' Ações Formativas Culturais: ações presenciais e gratuitas, destinadas a alunos e professores de instituições de ensino de qualquer nível, que visem a conscientização para a importância da arte e da cultura por intermédio do produto cultural do projeto.',92,0)
;