INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('CÓPIA AUTENTICADA CONTRATO SOCIAL/REQUERIMENTO EMPRESARIAL COM A FINALIDADE CULTURAL EXPRESSA.','0',1,1,1)
,('CÓPIA AUTENTICADA DOCUMENTOS DE IDENTIFICAÇÃO DO DIRIGENTE DA ENTIDADE PROPONENTE (RG E CPF OU CNH)','0',1,1,1)
,('CÓPIA AUTENTICADA DO ESTATUTO SOCIAL,CONTENDO A FINALIDADE CULTURAL EXPRESSA NOS SEUS OBJETIVOS','0',1,1,1)
,('CÓPIA AUTENTICADA DOS DOCUMENTOS DE IDENTIFICAÇÃO DO PROPONENTE ( RG E CPF OU CNH)','0',1,1,1)
,('Cópia autenticada do contrato social ou equivalente ','0',1,1,0)
,('CÓPIA AUTENTICADA DA ATA DE ELEIÇÃO DA ATUAL DIRETORIA E/OU TERMO DE POSSE DO ATUAL  DIRIGENTE.','0',1,1,1)
,('CÓPIA DO REGISTRO DO CNPJ, CONTENDO A ATIVIDADE CULTURAL REGISTRADA COMO PRIMÁRIA OU SECUNDÁRIA.','0',1,1,1)
,('FORMULÁRIO IMPRESSO NO PADRÃO DO SALICWEB.','0',2,1,0)
,('DECLARAÇÃO DE INCENTIVOS FISCAIS ASSINADA PELO PROPONENTE.','0',2,1,0)
,('Orçamento analítico, contendo especificações de todos os custos','0',2,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Plano básico de divulgação assinado pelo proponente.','0',2,1,0)
,('Cópia da pesquisa/estudo do que deverá ser criado','6',2,1,0)
,('CÓPIA AUTENTICADA DA ESCRITURA DO IMÓVEL','5',2,1,0)
,('Plano de distribuição de ingressos','1',2,1,0)
,('Número  de espetáculos','1',2,1,0)
,('Lotação dos teatros','1',2,1,0)
,('Valor dos ingressos','1',2,1,0)
,('CURRÍCULO DA EQUIPE TÉCNICA, ESPECIFICANDO AS FUNÇÕES NO PROJETO.','1',2,1,0)
,('Roteiro da temporada','1',2,1,0)
,('Período da temporada','1',2,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Trechos das passagens','1',2,1,0)
,('Número da participantes','1',2,1,0)
,('Número de diárias','1',2,1,0)
,('AUTORIZAÇÃO DO PROPRIETÁRIO OU DETENTOR DE DIREITOS OU CESSÃO DOS DIREITOS AUTORAIS.','0',2,1,1)
,('Roteiro','2',2,1,0)
,('RELATÓRIO DE ATIVIDADES CULTURAIS DA ENTIDADE/EMPRESA PROPONENTE.','0',1,1,1)
,('Análise técnica','2',2,1,0)
,('Plano de produção','2',2,1,0)
,('Certificado de registro na FBN','2',2,1,0)
,('Promessa de cessão de direito ou declaração de autencidade','2',2,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Contrato de co-produção registrado na Secretaria do Audiovisual','2',2,1,0)
,('Demonstrativo de receita','2',2,1,0)
,('Plano de distribuição/Acessibilidade conforme artigos 27 e 44 do Decreto 5.761/2006','0',2,1,0)
,('Datas locais dos shows','3',2,1,0)
,('Viabilidade técnica','2',2,1,0)
,('Viabilidade comercial','2',2,1,0)
,('Número de apresentações','3',2,1,0)
,('Plantas e croquis','2',2,1,0)
,('Catálogo de equipamentos','2',2,1,0)
,('Roteiro da tournée','3',2,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Período da tournée','3',2,1,0)
,('Número de participantes na tournée','3',2,1,0)
,('Autorização do autor da obra','3',2,1,0)
,('Declaração de regularidade fiscal e previdenciária (Firma reconhecida)','0',1,1,0)
,('Certidão conjunta de débitos relativos a tributos federais e à dívida ativa da união (Autenticado)','0',1,1,0)
,('CERTIDÃO DE QUITAÇÃO DE TRIBUTOS FEDERAIS -  CQTF','0',1,1,1)
,('CERTIDÃO NEGATIVA DE DÉBITOS DO FGTS','0',1,1,1)
,('CERTIDÃO NEGATIVA DE DÉBITOS DO INSS','0',1,1,1)
,('CURRÍCULO DO PROPONENTE COMPROVANDO AS ATIVIDADES CULTURAIS REALIZADAS.','0',1,1,1)
,('Cronograma de execução física','2',2,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Cronograma de desembolso','0',2,1,0)
,('Orçamento de comercialização','2',2,1,0)
,('Declaração de contrapartida','2',2,1,0)
,('Sinopse / Justificativa','2',2,1,0)
,('Autorização do proprietário dos bens a receberem as intervenções propostas no projeto;','5',2,1,0)
,('Registro documental, fotográfico ou videográfico dos bens a receberem as intervenções propostas','5',2,1,0)
,('Copia do ato de tombamento;','5',2,1,0)
,('Copia da escritura pública referente à área onde será executado o projeto registrada em cartório','5',2,1,0)
,('Relação dos bens a serem doados','5',2,1,0)
,('JOGO COMPLETO E DETALHADO DAS PROPOSTAS ARQUITETÔNICAS E COMPLEMENTARES DA INTERVENÇÃO.','5',2,1,1)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Documento comprobatório de estimativa de avaliação dos bens a serem doados','5',2,1,0)
,('ESPECIFICAÇÕES TÉCNICAS DAS PEÇAS GRÁFICAS.','6',2,1,0)
,('Orçamento de Comercialização (conforme art.8º da Port. 500 de 18/12/98 ).','2',2,1,0)
,('Carta de intenção da TV  para veiculação do programa','2',2,1,0)
,('Curriculum do produtor da obra (comprovando capacidade para realização do produto)','2',1,1,0)
,('Certidão de quitação de tributos Estaduais ( Cópia Autenticada)','0',1,1,0)
,('Certidão de quitação de tributos Municipais ( Cópia Autenticada)','0',1,1,0)
,('Relatório das atividades culturais da Instituição, no último exercício','0',1,1,0)
,('Ficha técnica do espetáculo','3',2,1,0)
,('Cadastro Geral do Proponente, conforme Cartas Circulares nº 228 e 230','2',1,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Relatório com resultados obtidos na última mostra ou festival','2',2,1,0)
,('Nome do diretor','2',2,1,0)
,('Nome do produtor','2',2,1,0)
,('Nome do roteirista','2',2,1,0)
,('Relação dos filmes a serem exibidos e as cartas de cessão de direitos','2',2,1,0)
,('Inclusão do item de custo da auditoria no orçamento - I.N. nº 1 de 03/05/2000. (www.minc.gov.br)','2',2,1,0)
,('Detalhamento (financeiro) do item de pesquisa, constante do orçamento','6',2,1,0)
,('SINOPSE DA OBRA.','6',2,1,0)
,('Estrutura/formato do programa, contendo sua duração e periodicidade','2',2,1,0)
,('Resumo das fontes de financiamento','6',2,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Sinopse do Texto','1',2,1,0)
,('Regularização junto ao CADIN, conforme demonstrativo de pendência em anexo','0',1,1,0)
,('Orçamento analítico / Cronograma físico e financeiro','6',2,1,0)
,('Auditoria Externa','6',2,1,0)
,('Contrato de cessão de direitos autorais','6',1,1,0)
,('Cópia autenticada do 1º contrato social e demais alterações ','2',1,1,0)
,('RELAÇÃO DO(S) BENEFICIÁRIO(S) DOS DIREITOS AUTORAIS DA OBRA A SER PUBLICADA.','6',2,1,0)
,('Termo de compromisso assinado pelo proponente','2',2,1,0)
,('Orçamento analítico','6',2,1,0)
,('Cronograma fisíco','6',2,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Contrato de cessão / Termo de anuência','6',2,1,0)
,('Resumo geral do orçamento','6',2,1,0)
,('Cronograma financeiro','6',2,1,0)
,('PLANO DE DISTRIBUIÇÃO','6',2,1,1)
,('Estrutura do Site','2',2,1,0)
,('Carta de intenção da empresa ou produtor responsável pela execução do projeto','2',2,1,0)
,('Relatório trimestral de captação fisíco e financeiro do ano anterior','2',2,1,0)
,('Carta de intenção de investimento/patrocínio, com valor e data do aporte dentro do exercício','2',2,1,0)
,('Devolução de saldo ao FNC','0',3,1,0)
,('Ausência, inconsistência e/ou insuficiência do relatório de execução física-financeira','0',3,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Ausência, inconsistência e/ou insuficiência do demonstrativo de execução de receita e despesa','0',3,1,0)
,('Ausência, inconsistência e/ou insuficiência da relação de pagamentos','0',3,1,0)
,('Ausência, inconsistência e/ou insuficiência da relação de bens adquiridos/construídos','0',3,1,0)
,('Ausência, inconsistência e/ou insuficiência da conciliação bancaria','0',3,1,0)
,('Ausência, inconsistência e/ou insuficiência do extrato bancário da conta do projeto','0',3,1,0)
,('Ausência, inconsistência e/ou insuficiência do relatório de cumprimento do objeto','0',3,1,0)
,('Não utilização de conta bancária específica','0',3,1,0)
,('Atraso injustificado para apresentação de prestação de contas','0',3,1,0)
,('Fatos e situações apontados pelos controles interno e externo sem prejuízos ao erário','0',3,1,0)
,('Falhas na guarda e manutenção de documentos comprobatórios de despesas','0',3,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Não encaminhamento ou envio intempestivo de recibos de captação','0',3,1,0)
,('Incompatibilidade entre a execução físico-financeira à programação aprovada','0',3,1,0)
,('Outras fatos e situações sem prejuízo ao erário','0',3,1,0)
,('Não demonstração da aplicação da contrapartida','0',3,1,0)
,('Aplicação dos recursos em finalidade diversa da estabelecida','0',3,1,0)
,('Não cumprimento do objeto','0',3,1,0)
,('Sem alcance dos objetivos','0',3,1,0)
,('Descumprimento às normas legais para licitaçãode produtos e/ou serviços','0',3,1,0)
,('Desaprovação de valores aplicados em taxa de administração, gerência ou similar (convênios)','0',3,1,0)
,('Incompatibilidade entre a execução-financeira e o plano de trabalho aprovado','0',3,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Incompatibilidade entre a execução-financeira e metas estabelecidas (plano de trabalho)','0',3,1,0)
,('Rejeição a recursos aplicados em consultorias, assistência técnica a servidor da administração','0',3,1,0)
,('Rejeição a valores aplicados em multas, taxas bancárias, juros e correção monetária','0',3,1,0)
,('Rejeição a despesas realizadas antes ou depois da vigência','0',3,1,0)
,('Omissão no dever de prestar contas','0',3,1,0)
,('Celebração de convênios com mais de um órgão para cumprimento de mesmo objeto','0',3,1,0)
,('Não devolução de saldo de recursos','0',3,1,0)
,('Diligência e/ou denúncia de fatos gravosos ao erário','0',3,1,0)
,('Diligência e/ou denúncia sobre ilegalidade material na gestão de recursos públicos','0',3,1,0)
,('Descumprimento a diligência do Ministério da Cultura','0',3,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Outros fatos e situações que tenham causados prejuízo ao erário','0',3,1,0)
,('Logomarca não atende disposição normativa','0',3,1,0)
,('Ausência de contrato de auditoria externa','0',3,1,0)
,('Ausência de solicitação de liberação da conta bancária','0',3,1,0)
,('Pagamentos indevidos','0',3,1,0)
,('Relatório de auditoria','0',3,1,0)
,('Cópia do ato de tombamento / Número do processo de tombamento','5',2,1,0)
,('Plantas baixas','5',2,1,0)
,('Cortes / Elevações','5',2,1,0)
,('Fachadas / Vistas','5',2,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Identificação do autor do projeto (nome, telefone e endereço)','5',2,1,0)
,('CREA do autor do projeto','5',2,1,0)
,('Assinatura do autor do projeto arquitetônico','5',2,1,0)
,('Endereço do imóvel','5',2,1,0)
,('Memorial descritivo (assinado pelo responsável pela obra)','5',2,1,0)
,('Especificar o item viagens e diárias, informando nome e função no evento e o trecho a ser percorrido','2',2,1,0)
,('Contrato firmado com o Incentivador','0',2,1,0)
,('Relacionar detalhadamente as metas executadas e informar as que serão realizadas no próximo período','3',2,1,0)
,('Informar o período para a realização do evento','3',2,1,0)
,('Informar as metas a serem realizadas','0',2,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Lay out do espaço no qual será realizada a exposição','4',2,1,0)
,('Relatório fotográfico das peças a serem expostas','4',2,1,0)
,('Data da exposição','4',2,1,0)
,('Local onde será realizada a exposição','4',2,1,0)
,('Tiragem do produto','3',2,1,0)
,('Datas e locais das apresentações','1',2,1,0)
,('Autorização do(s) detentor(es) dos direitos autorais ou da SBAT','1',2,1,0)
,('Projeto arquitetônico completo assinado pelo responsável da obra','5',2,1,0)
,('Acordo de Cooperação Técnica- via original com firma reconhecida em cartório.','5',2,1,0)
,('Cópia autenticada da Escritura Pública ','5',2,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Relatório Fotográfico (obra continuada)','5',2,1,0)
,('Projetos Complementares','5',2,1,0)
,('Previsão de custo, no orçamento,  do envio dos livros relativos à contrapartida (10%).','6',2,1,0)
,('Balanços contábeis do exercício anterior','0',1,1,0)
,('Lei orçamentária do exercício anterior','0',1,1,0)
,('Orçamento do ano corrente indicando a contrapartida','0',1,1,0)
,('Resumo das Fontes de Financiamento','0',2,1,0)
,('Resumo Geral do Orçamento','0',2,1,0)
,('Termo de compromisso para captação de recursos com assinatura legível.','0',1,1,0)
,('Informar as metas já realizadas','0',2,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Informar o nº de dias necessários para realização das metas','0',2,1,0)
,('Formulário de solicitação preenchido','0',4,1,0)
,('Termo de compromisso assinado pelo solicitante, quando se tratar de grupo, por cada membro do grupo','0',4,1,0)
,('Cópias autenticadas da Carteira de Identidade e CPF do proponente e dos demais membros do grupo','0',4,1,0)
,('Currículo do solicitante, ou do grupo, com anexos comprabátorios','0',4,1,0)
,('Convite oficial do evento firmado pela entidade organizadora, com tradução, se for o caso','0',5,1,0)
,('Programação do evento, com tradução, se for o caso','0',5,1,0)
,('Duas cartas de recomendação versando sobre o trabalho e qualificações profissionais do candidato','0',5,1,0)
,('PROJETO PEDAGÓGICO, ACOMPANHADO DO CURRÍCULO DO RESPONSÁVEL.','0',2,1,1)
,('AUTORIZAÇÃO DO ÓRGÃO PÚBLICO COMPETENTE, NO CASO DE EVENTOS EM ESPAÇOS PÚBLICOS.','0',2,1,1)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('MEDIDAS PREVENTIVAS ADOTADAS PARA EVITAR IMPACTO AMBIENTAL NEGATIVO, CASO EVENTO AO AR-LIVRE.','0',2,1,0)
,('Informar detalhadamente os locais das apresentações e como será a acomodação do público','0',2,1,0)
,('CÓPIA AUTENTICADA ATO DE TOMBAMENTO, CASO DE INTERVENÇÃO EM IMÓVEIS TOMBADOS PELOS PODERES PÚBLICO','5',2,1,1)
,('REGISTRO DOCUMENTAL FOTOGRÁFICO OU VIDEOGRÁFICO DA SITUAÇÃO ATUAL DOS BENS A RECEBEREM A INTERVENÇÃO','5',2,1,1)
,('Data de realização do evento','0',2,1,0)
,('Local onde será realizado o evento','0',2,1,0)
,('Agência Bancária do Banco do Brasil','0',2,1,0)
,('Planilha orçamentária conforme modelo disponibilizado no site www.cultura.gov.br','0',2,1,0)
,('FICHA TÉCNICA, ACOMPANHADA DE CURRÍCULO DO(S) CURADOR(ES)','4',2,1,0)
,('PLANO DE EXECUÇÃO DAS OFICINA(S) E/OU WORKSHOP(S), CONTENDO CARGA HORÁRIA E CONTEÚDO PROGRAMÁTICO.','0',2,1,1)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('CÓPIA AUTENTICADA DA PROCURAÇÃO OU AUTORIZAÇÃO DO PROPONENTE','0',1,1,1)
,('CÓPIA DO CERTIFICADO DE REGISTRO DO ROTEIRO NA FUNDAÇÃO BIBLIOTECA NACIONAL(NO CASO DE FICÇÃO)','2',2,1,1)
,('PROPOSTA DE INTERVENÇÃO APROVADA PELO ÓRGÃO RESPONSÁVEL PELO TOMBAMENTO.','5',2,1,1)
,('AUTORIZAÇÃO DO PROPIETÁRIO DO IMOVEL/COMPROVAÇÃO DA POSSE,POR INTERESSE PUBLICO/SOCIAL POR 20 ANOS.','5',2,1,1)
,('REGISTRO DOCUMENTAL DAS ESPECIFICAÇÕES TÉCNICAS DOS MATERIAIS E EQUIPAMENTOS UTILIZADOS.','5',2,1,1)
,('CONTRATO OU ACORDO DE COOPERAÇÃO TECNICA, CASO DE EXECUÇÃO COMPARTILHADA','5',2,1,1)
,('LEVANTAMENTO ARQUITETÔNICO COMPLETO, ESPECIFICANDO POSSIVEIS DANOS EXISTENTES AO BEM TOMBADO.','5',2,1,1)
,('LISTAGEM DOS BENS CASO A PROPOSTA VISE IDENTIFICAÇÃO,DOCUMENTAÇÃO E INVENTÁRIO DE BEM MATERIAL.','5',2,1,1)
,('INVENTÁRIO DO ACERVO E PARECER OU LAUDO TÉCNICO SOBRE O ACERVO.','5',2,1,1)
,('TERMO DE COMPROMISSO, ATESTANDO QUE O RESULTADO SERÁ INTEGRADO SEM ÔNUS AO BANCO DE DADOS DO IPHAN.','5',2,1,1)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('CÓPIA AUTENTICADA DOS DOCUMENTOS DE IDENTIFICAÇÃO DO PROCURADOR ( RG E CPF OU CNH)','0',1,1,1)
,('RELATÓRIO FOTOGRÁFICO DAS OBRAS QUE SERÃO EXPOSTAS','4',2,1,1)
,('PROPOSTA MUSEOGRÁFICA DA EXPOSIÇÃO','4',2,1,1)
,('FORMULÁRIO IMPRESSO NO PADRÃO DO SALICWEB (FORMATO PAISAGEM).','0',2,1,0)
,('Pré-roteiro/Argumento','2',2,1,0)
,('Story Board','2',2,0,0)
,('Descrição das fontes de alimentação de conteúdo','2',2,1,0)
,('Definição de conteúdos (pesquisa e sua organização e roteiros);','2',2,1,0)
,('Design das interfaces, descrição da navegabilidade, opções de interatividade','2',2,1,0)
,('Sinopse e modelo de roteiro do programa, dividido por blocos e pautas/temas','2',2,1,0)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('Projeto Pedagógico, acompanhado do currículo do responsável','2',2,1,0)
,('Laudo técnico do estado das obras a serem restauradas','2',2,0,0)
,('Termo de comprometimento de entrega de um master para preservação na Cinemateca Brasileira','2',2,0,0)
,('Currículo da equipe técnica especificando as suas funções a serem desempenhadas no projeto','0',2,1,1)
,('Três orçamentos obtidos no mercado, no caso de propostas que contenham previsão de aquisição de bens','2',2,0,0)
,('FICHA TÉCNICA','0',2,1,0)
,('CURRÍCULO(S) DO(S) DIRETOR(ES) ARTÍSTICO(S) E DO(S) GRUPO(S)/ARTISTA(S) PARTICIPANTES DO PROJETO','0',2,1,0)
,('MEMORIAL DESCRITIVO DETALHADO, ASSINADO PELO AUTOR DA PROPOSTA','5',2,1,1)
,('ROTEIRO DIVIDIDO POR SEQÜÊNCIAS, CONTENDO O DESENVOLVIMENTO DOS DIÁLOGOS (NO CASO DE FICÇÃO)','2',2,1,1)
,('PLANTA DE SITUAÇÃO DO IMÓVEL','5',2,1,1)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('CÓPIA AUTENTICADA DA ESCRITURA DO IMÓVEL, QUANDO O PROPOSTA ENVOLVER INTERVENÇÃO EM BENS IMÓVEIS','5',2,1,1)
,('AUTORIZAÇÃO PARA REALIZAÇÃO DA OBRA, PELA AUTORIDADE COMPETENTE','5',2,1,1)
,('Detalhamento de despesas','0',2,1,1)
,('RELAÇÃO DOS TÍTULOS A SEREM EXIBIDOS E SUAS RESPECTIVAS AUTORIZAÇÕES','2',2,1,1)
,('INFORMAÇÕES ADICIONAIS','0',2,1,1)
,('Carta de Apoio dos membros da comunidade onde o candidato atua','0',1,1,1)
,('Materiais diversos que comprovem a atuação do candidato','0',2,1,1)
,('Carta ao proponente','0',2,1,1)
,('INFORMAÇÃO DE REGULARIZAÇÃO NO CADIN','0',1,1,1)
,('CRONOGRAMA DE EXECUÇÃO ATUALIZADO','0',2,1,1)
;
INSERT INTO SAC.dbo.DocumentosExigidos (Descricao,Area,Opcao,stEstado,stUpload) VALUES 
('NOVO PLANO DE DISTRIBUIÇÃO DE PRODUTOS CULTURAIS','0',2,1,1)
,('INFORMAÇÃO DE REGULARIZAÇÃO NO CEPIM','0',1,1,1)
,('RESULTADO DA SELEÇÃO PÚBLICA','0',2,1,1)
;