INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(7,'Público',0)
,(7,'Privado com fins lucrativo',0)
,(8,'Municipal',0)
,(8,'Estadual',0)
,(8,'Federal',0)
,(9,'Executivo',0)
,(9,'Legislativo',0)
,(9,'Judiciário',0)
,(10,'Direta',0)
,(10,'Indireta',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(11,'ONG',0)
,(11,'OSCIP',0)
,(11,'Órgão Gestor de Cultura',0)
,(1,'Nome de Registro',0)
,(1,'Razão Social',0)
,(1,'Nome Fantasia',0)
,(1,'Apelido',0)
,(2,'Residencial',0)
,(2,'Comercial',0)
,(3,'Residencial',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(3,'Comercial',0)
,(3,'Celular',0)
,(3,'Fax',0)
,(4,'E-mail Particular',0)
,(4,'E-mail Institucional',0)
,(5,'Carteira de Identidade',0)
,(5,'Título de Eleitor',0)
,(7,'Privado sem fins lucrativo',0)
,(4,'Blog',0)
,(4,'Orkut',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(4,'Site',0)
,(1,'Nome Artístico',0)
,(13,'Avenida',0)
,(13,'Praça',0)
,(13,'Quadra',0)
,(13,'Rua',0)
,(13,'Outros',0)
,(14,'Prefeitura',0)
,(14,'Biblioteca',0)
,(14,'Ponto de Cultura',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(11,'Conselho/Órgão Colegiado de Cultura',13)
,(14,'Museu',0)
,(14,'Instituto',0)
,(14,'Fundação',0)
,(14,'Forum de Cultura',0)
,(14,'Secretaria',0)
,(14,'Empresa',0)
,(14,'Griôs',0)
,(14,'Vago',0)
,(14,'Departamento',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(14,'Agência',0)
,(11,'Órgão de Administração Municipal',0)
,(11,'Órgão de Administração Estadual',0)
,(11,'Órgão de Administração Federal',0)
,(13,'Largo',0)
,(13,'Alameda',0)
,(13,'Ladeira',0)
,(11,'Empresa Privada',0)
,(11,'Conselho/Órgão Colegiado de Patrimônio Cultural',13)
,(11,'Conselho/Órgão Colegiado Setorial de Artes',13)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(11,'Conselho/Órgão Colegiado de Incentivo à Cultura',13)
,(11,'Conselho/Órgão Colegiado Setorial de Artes Visuais',13)
,(11,'Conselho/Órgão Colegiado Setorial de Artes Cênicas',13)
,(11,'Conselho/Órgão Colegiado Setorial de Artes do Espetáculo',13)
,(11,'Conselho/Órgão Colegiado Setorial de Música',13)
,(11,'Conselho/Órgão Colegiado Setorial de Dança',13)
,(11,'Conselho/Órgão Colegiado Setorial de Teatro',13)
,(11,'Conselho/Órgão Colegiado Setorial de Circo',13)
,(11,'Conselho/Órgão Colegiado Setorial do Audiovisual',13)
,(11,'Conselho/Órgão Colegiado Setorial do Livro e Leitura',13)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(11,'Conselho/Órgão Colegiado Setorial de Museus e Arquivos',13)
,(11,'Conselho/Órgão Colegiado Setorial de Museu(s)',13)
,(11,'Conselho/Órgão Colegiado Setorial de Arquivo(s)',13)
,(11,'Conselho/Órgão Colegiado Setorial de Biblioteca(s) Pública(s)',13)
,(11,'Conselho/Órgão Colegiado Setorial de Centro(s) Cultural(is)',13)
,(11,'Conselho/Órgão Colegiado Setorial de Região Urbana',13)
,(11,'Conselho/Órgão Colegiado Setorial de Micro/Mesorregião',13)
,(11,'Conselho/Órgão Colegiado Setorial de Distrito Municipal',13)
,(11,'Órgao Consultivo/Deliberativo de Cultura',13)
,(11,'Conselho/Órgão Colegiado Setorial de Culturas Indígenas',13)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(11,'Conselho/Órgão Colegiado Setorial de Culturas Afro-Brasileira',13)
,(11,'Conselho/Órgão Colegiado Setorial da Cultura GLTB',13)
,(14,'Empresa',0)
,(11,'Empresa Pública',0)
,(14,'Servidor Público',3)
,(11,'Servidor Público Federal',3)
,(11,'Servidor Público Estadual',3)
,(11,'Servidor Público Municipal',3)
,(11,'Servidor do Programa Monumenta',3)
,(11,'Servidor Consultor de Órgão Internacional',3)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(11,'Servidor Vigilante',3)
,(11,'Servidor Motorista',3)
,(13,'Aeroporto',0)
,(13,'Área',0)
,(13,'Campo',0)
,(13,'Chácara',0)
,(13,'Colônia',0)
,(13,'Condomínio',0)
,(13,'Conjunto',0)
,(13,'Distrito',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(13,'Esplanada',0)
,(13,'Estação',0)
,(13,'Estrada',0)
,(13,'Favela',0)
,(13,'Fazenda',0)
,(13,'Feira',0)
,(13,'Jardim',0)
,(13,'Lago',0)
,(13,'Lagoa',0)
,(13,'Loteamento',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(13,'Morro',0)
,(13,'Núcleo',0)
,(13,'Parque',0)
,(13,'Passarela',0)
,(13,'Pátio',0)
,(13,'Recanto',0)
,(13,'Residência',0)
,(13,'Rodovia',0)
,(13,'Setor',0)
,(13,'Sítio',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(13,'Travessa',0)
,(13,'Trecho',0)
,(13,'Vale',0)
,(13,'Vereda',0)
,(13,'Via',0)
,(13,'Viaduto',0)
,(13,'Viela',0)
,(13,'Vila',0)
,(16,'Proponente',21)
,(16,'Incentivador',21)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(16,'Servidor',21)
,(14,'Prestadores de Serviços',3)
,(11,'Servidor de Limpeza',3)
,(16,'Órgãos de Cultura',13)
,(14,'Conselho',13)
,(11,'Órgão Colegiado Setorial',13)
,(11,'Órgão Colegiado',13)
,(11,'Órgao Consultivo',13)
,(11,'Órgão Deliberativo',13)
,(16,'Operadora do Ticket Cultural',4)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(16,'Doadora do Ticket Cultural',4)
,(17,'Certidão de Quitação de Tributos Municipais',12)
,(17,'Certidão de Quitação de Tributos Estaduais',12)
,(17,'Certidão Conjunta Negativa de Tributos Federais e Dívida Ativa da União',12)
,(17,'Certidão Negativa de Débitos junto ao INSS',12)
,(17,'Certidão Negativa de Débitos junto ao FGTS',12)
,(16,'Poder Executivo Municipal',0)
,(16,'Poder Executivo Estadual',0)
,(16,'Poder Executivo Federal',0)
,(16,'Cadastro',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(11,'Nenhum',0)
,(1,'Sigla',0)
,(16,'Cultura Viva',0)
,(16,'Mala Direta',0)
,(4,'Grupo de e-mail',0)
,(5,'Registro Profissional',0)
,(5,'Carteira de Trabalho',0)
,(16,'Diversidade Cultural',0)
,(14,'Inclusão Cultural da Pessoa Idosa',0)
,(14,'Governo Estadual',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(14,'Governo Federal',0)
,(20,'Ficha de inscrição devidamente preenchida',0)
,(18,'Cópia autenticada da carteira de identidade',0)
,(18,'Cópia autenticada do CPF',0)
,(18,'Curriculum Vitae',0)
,(20,'Carta de recomendação de autoridade na área cultural endossando a iniciativa',0)
,(20,'Material complementar sobre a iniciativa: matérias de jornal, DVDs, CDs, fotos, folders, cartazes',0)
,(19,'Cópia autenticada do estatuto da instituição e alterações, se houver',0)
,(19,'Cópia autenticada do termo de posse do dirigente em exercício',0)
,(19,'Cópia autenticada do cartão do CNPJ',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(19,'Cópia autenticada da carteira de identidade do dirigente em exercício',0)
,(19,'Cópia autenticada do CPF do dirigente em exercício',0)
,(19,'Relatório das atividades da instituição na área cultural',0)
,(14,'Prêmio Culturas Ciganas',0)
,(14,'Prêmio Culturas Populares',0)
,(19,'Cópia autenticada da última alteração',0)
,(20,'Termo de responsabilidade assinado',0)
,(16,'Parceiro de Projeto Cultural',0)
,(16,'Dirigente de Instituição',21)
,(16,'Beneficiário de produtos do projeto cultural',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(16,'Interviniente',0)
,(20,'Cópia autenticada de comprovante de endereço atualizado',0)
,(20,'Proponente habilitado de acordo com o edital',0)
,(16,'Vago',0)
,(14,'Seção',0)
,(14,'Coordenação',0)
,(14,'Gerência',0)
,(14,'Divisão',0)
,(14,'Diretoria',0)
,(16,'Parecerista de projeto cultural',21)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(16,'Componente da Comissão',21)
,(16,'Avaliador de Edital',0)
,(16,'Representantes na CNIC',0)
,(16,'Coord Acompanhamento',0)
,(16,'Coord Parecerista',0)
,(16,'Vago',0)
,(16,'Tecnico',21)
,(16,'Votantes da Cnic',21)
,(21,'Ensino Fundamental',0)
,(21,'Ensino Médio',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(21,'Ensino Superior - Biblioteconomia',0)
,(21,'Ensino Superior - Outros',0)
,(21,'Especialização',0)
,(21,'Mestrado',0)
,(21,'Doutorado',0)
,(22,'Efetivo',0)
,(22,'Cedido',0)
,(22,'Temporário',0)
,(22,'Terceirizado',0)
,(22,'Voluntário',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(22,'Estagiário ou Bolsista',0)
,(23,'0',0)
,(23,'De 0 a 499',0)
,(23,'De 500 a 1499',0)
,(23,'De 1500 a 2499',0)
,(23,'De 2500 a 2999',0)
,(23,'De 3000 a 4999',0)
,(23,'De 5000 a 6999',0)
,(23,'De 7000 a 8999',0)
,(23,'De 9000 a 10999',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(23,'De 11000 acima',0)
,(24,'Diretoria',0)
,(24,'Corpo Técnico',0)
,(24,'Administrativo',0)
,(24,'Manutenção',0)
,(16,'SNIIC',0)
,(14,'Proprietário/Mantenedor',0)
,(16,'Procurador ',21)
,(16,'Fornecedor',21)
,(25,'Nivel I',0)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(25,'Nivel II',0)
,(25,'Nivel III',0)
,(24,'Secretário de Fomento e Incentivo à Cultura',21)
,(24,'Secretário de Fomento e Incentivo à Cultura - Substituto',21)
,(24,'Secretário do Audiovisual',21)
,(24,'Secretário do Audiovisual - Substituto',21)
,(26,'Henilton Parente de Menezes',21)
,(26,'Leopoldo Nunes da Silva Filho',21)
,(26,'João Batista da Silva',21)
,(26,'Jorge Alan Pinheiro Guimarães',21)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(26,'Kleber da Silva Rocha',21)
,(26,'João Batista da Silva',21)
,(27,'Secretário(a)',21)
,(27,'Diretor(a) Substituto(a)',21)
,(27,'Coordenador-Geral de Desenvolvimento Controle e Avaliação',21)
,(27,'Coordenador(a) Técnico do Pronac',21)
,(16,'Servidor Comissionado',21)
,(27,'Coordenador(a)',21)
,(27,'Coordenador(a)-Geral',21)
,(27,'Ordenador(a) de Despesas-substituto(a)',21)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(26,'Flávia Rodrigues Dias',21)
,(26,'Cleide Lopes de Oliveira',21)
,(26,'Antônio Carlos Silva',21)
,(26,'Ana Cristina da Cunha Wanzeler ',21)
,(27,'Agente Administrativo',21)
,(27,'Coordenador(a)-Geral Substituto(a)',21)
,(27,'Ordenador(a) de Despesas',21)
,(27,'Coordenador(a)-substituto(a)',21)
,(27,'Chefe de divisão',21)
,(3,'Telefone - Receita Federal',21)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(1,'Nome - Receita Federal',21)
,(2,'Endereço - Receita Federal',21)
,(4,'Internet - Receita Federal',21)
,(13,'Logradouro - Receita Federal',21)
,(27,'Diretor(a)',21)
,(27,'Comissário(a) Relator(a)',21)
,(27,'Parecerista',21)
,(27,'Superintendente',21)
,(27,'Presidente',21)
,(27,'Presidente - Substituto(a)',21)
;
INSERT INTO Agentes.dbo.Verificacao (IdTipo,Descricao,Sistema) VALUES 
(27,'Secretário(a) - Substituto(a)',21)
,(27,'Técnico',21)
,(16,'Portador de cartão de pagamento',21)
;