INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(1,'Anúncio de  página dupla',1)
,(1,'Apostila',1)
,(1,'Apresentação multimídia ',1)
,(1,'Arte slide/insert',1)
,(1,'Audiovisual 3'' a 5''',1)
,(1,'Back-drop/paínel',1)
,(1,'Back-light/front-light/empenas de prédios',1)
,(1,'Banner/faixa adesiva/faixa de lona/saia de palco/testeira/pórtico',1)
,(1,'Boletim',1)
,(1,'Broadside por página',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(1,'Busdoor (vidro traseiro)',1)
,(2,'TV',1)
,(2,'Mídia Exterior',1)
,(2,'Impressos',1)
,(2,'Jornal',1)
,(2,'Revista',1)
,(2,'Internet',1)
,(1,'Adesivo de chão',1)
,(1,'Album/book',1)
,(1,'Anúncio de 1 de página',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(1,'Anúncio de 1/2 de  página',1)
,(1,'Anúncio de 1/3 de página',1)
,(1,'Anúncio de 1/4 de página',1)
,(1,'Anúncio de 2/3 de página',1)
,(3,'Na parte interna da capa',1)
,(3,'Na primeira página de apresentação',1)
,(3,'Na contracapa',1)
,(3,'Junto ao expediente',1)
,(3,'Na última capa do folheto',1)
,(3,'Na contracapa da caixa',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(3,'Antes dos letreiros de apresentação',1)
,(3,'Antes dos créditos finais',1)
,(3,'Na capa dos vídeos cassetes',1)
,(3,'Durante a locução e no final em peça pré-gravada',1)
,(3,'Na locução de apresentação',1)
,(3,'Nos créditos finais',1)
,(3,'Ao final do comercial',1)
,(3,'Na parte inferior direita junto c/a logomarca do governo federal',1)
,(1,'Caderno',1)
,(1,'Calendário/folinha por lâmina',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(1,'Capa de caderno/livro/Revista/ Relaório/Catálogo/Carilha Manual Técnico',1)
,(1,'Capa de CD/DVD/Rótulo de CD/DVD/Adesivo de CD',1)
,(1,'Cartaz/Poster',1)
,(1,'Cartazete',1)
,(1,'Cartilha',1)
,(1,'Catalogo',0)
,(1,'CD_ROM',1)
,(1,'Circular/carta',1)
,(1,'Convite',1)
,(1,'Convite Eletrônico/Folder Eletrônico',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(1,'E-Mail',1)
,(1,'Encarte de CD por página',1)
,(1,'Envelopamento ônibus',1)
,(1,'Envelopamento taxi',1)
,(1,'Etiqueta/Adesivo/Etiqueta de Bagagem',1)
,(1,'Faixa',1)
,(1,'Filme/VT Institucional acima de 30"/Informativo Eletrônico',1)
,(1,'Filme/VT Institucional até 30"',1)
,(1,'Folder formato até A1(84x59,4cm)',1)
,(1,'Folder formato até A2(59,4x42cm)',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(1,'Folder formato até A3(29,7x42cm)',1)
,(1,'Folder formato até A4(21x29,7cm)',1)
,(1,'Folder formato até A5(15,5x21cm)',1)
,(1,'Folheto',1)
,(1,'Jingle acima de 30"',1)
,(1,'Jingle de até 30"',1)
,(1,'Jornal / Encarte de jornal',1)
,(1,'Lateral de Onibus',1)
,(1,'Livreto',1)
,(1,'Livro',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(1,'Luminoso teto de táxi',1)
,(1,'Manual Técnico',1)
,(1,'Outdoor simples',1)
,(1,'Painel externo metrô',1)
,(1,'Paínel Frontal de Ponto de Onibus',1)
,(1,'Paínel Lateral de Ponto de Onibus',1)
,(1,'Peças de Audio',1)
,(1,'Peças de Internet(criação/textos/frames/multmídia)',1)
,(1,'Placa de Estrada, de Obra e de Sinalização',1)
,(1,'Placa de rua (esquina)',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(1,'Revista / Encarte de revista',1)
,(1,'Sítio de internet',1)
,(1,'Spot acima de 30"',1)
,(1,'Spot de até 15"',1)
,(1,'Spot de até 30"',1)
,(1,'Testeira de Ponto de Onibus',1)
,(1,'Traseira de Onibus',1)
,(1,'Traseira de taxi (vidro)',1)
,(1,'VT varejo acima de 30"/Vinhetas acima 30"',1)
,(1,'VT varejo até 15"/Vinheta até 15"',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(1,'VT varejo até 30"/Vinheta até 30"',1)
,(4,'Proposta com o proponente',1)
,(4,'Proposta para Análise Inicial',1)
,(4,'Proposta em Conformidade Visual e / ou Análise Documental ',1)
,(6,'Pendência documental',1)
,(5,'Recursos Privados de Terceiros',1)
,(5,'Recursos de Organização não governamental',1)
,(5,'Recursos de Organismo internacional',1)
,(5,'Recursos da Administração Municipal',1)
,(5,'Recursos da Administração Estadual',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(5,'Recursos da Administração Federal',1)
,(6,'Não há pendência documental',1)
,(6,'Informar o nº do projeto',1)
,(5,' Incentivo Fiscal Federal',1)
,(6,'Outros assuntos',0)
,(6,'Outro assunto',0)
,(5,'Incentivo Fiscal Estadual',1)
,(5,'Incentivo Fiscal Municipal',1)
,(5,'Recursos Privados Próprios',1)
,(6,'Rádio',0)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(6,'Rádio',0)
,(6,'rádio',0)
,(2,'Rádio',1)
,(1,'Anúncio de Rodapé',1)
,(1,'Display',1)
,(7,'Edíficio Sede',1)
,(7,'Edifício Elcy Meireles',1)
,(7,'Edifício 502 Sul',1)
,(8,'Diligência na Análise Técnica Inicial',1)
,(6,'Diligências',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(8,'Diligência na CNIC - Análise Inicial',1)
,(4,'Proposta encaminhada para apreciação do Coordenador',1)
,(4,'Proposta em Análise Final ',1)
,(10,'Recurso de Prorrogação',1)
,(11,'Alteração do nome do projeto',1)
,(11,'Alteração da razão social',1)
,(11,'Alteração do proponente',1)
,(11,'Alteração do local de realização',1)
,(12,'Programa Cultura Viva',1)
,(12,'Audiovisual',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(12,'GLTB',1)
,(12,'Culturas Populares',1)
,(12,'Pessoa Idosa',1)
,(12,'Cultura Indígena',1)
,(13,'Prêmio',1)
,(13,'Concurso',1)
,(12,'Curta Metragem (Audiovisual)',1)
,(12,'Documentário (Audiovisual)',1)
,(12,'Mais Cinema (Audiovisual)',1)
,(12,'Longa Metragem (Audiovisual)',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(12,'Roteiro (Audiovisual)',1)
,(12,'Comercialização (Audiovisual)',1)
,(14,'Incentivo Fiscal',0)
,(14,'Convênio',1)
,(14,'Edital',1)
,(14,'Emenda Parlamentar',1)
,(12,'Circuito de Música Popular',1)
,(12,'Conexões Visuais',1)
,(12,'Residências em Artes Cênicas',1)
,(12,'Estímulo às Artes Cênicas- Circo, Dança e Tetro',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(12,'Myriam Muniz',1)
,(12,'Carequinha de Estímulo ao Circo',1)
,(15,'Fundo Nacional de cultura',1)
,(15,'Fundo Setorial de Artes Visuais',1)
,(15,'Fundo Setorial de Dança, Teatro e Circo',1)
,(15,'Fundo Setorial de Música',1)
,(15,'Fundo Setorial de Acesso e Diversidade',1)
,(15,'Fundo Setorial de Patrimônio e Memória',1)
,(15,'Fundo Setorial de Livro, Leitura, Literatura e Língua Portuguesa',1)
,(15,'Fundo Setorial de Incentivo à Inovação  do Audiovisual',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(15,'Fundo Setorial de Ações Transversais e Equalização de Políticas Culturais',1)
,(8,'Diligência na readequação - Técnico',1)
,(8,'Diligência na fiscalização',1)
,(8,'Diligência na avaliação - Relatório Trimestral',1)
,(8,'Diligência na prestação de contas',1)
,(13,'Auxílio',1)
,(6,'Arquivamento de proposta cultural',1)
,(9,'Despacho de Admissibilidade',1)
,(13,'Bolsa',1)
,(6,'Informar nº Pronac do Edital',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(6,'Arquivamento de Proposta de Edital',1)
,(8,'Diligência na CNIC - Readequação',1)
,(8,'Diligência na readequação - Parecerista',1)
,(8,'Diligência na movimentação bancária',1)
,(17,'VIDEOARTE: ATÉ R$ 30.000,00',1)
,(17,'PRODUÇÃO LONGA METRAGEM DE DOCUMENTÁRIO PARA SALA DE CINEMA: ATÉ R$ 350.000,00',1)
,(17,'PRODUÇÃO LONGA DE FICÇÃO E ANIMAÇÃO PARA SALA DE CINEMA: ATÉ R$ 800.000,00',1)
,(17,'REALIZAÇÃO DE CURTA METRAGEM EM DIGITAL ALTA DEFINIÇÃO ? ESTREANTE: ATÉ R$ 40.000,00',1)
,(17,'REALIZAÇÃO DE CURTA METRAGEM EM HD (TV, INTERNET): ATÉ R$ 60.000,00',1)
,(17,'REALIZAÇÃO DE CURTA METRAGEM SALA DE CINEMA: ATÉ R$ 110.000,00',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'REALIZAÇÃO DE OBRA PARA TELEVISÃO (26 MIN): ATÉ R$ 50.000,00',1)
,(17,'REALIZAÇÃO DE OBRA PARA TELEVISÃO (52 MIN): ATÉ R$ 100.000,00',1)
,(17,'FINALIZAÇÃO DE LONGA METRAGEM FICÇÃO, ANIMAÇÃO E DOCUMENTÁRIO: ATÉ R$ 200.000,00',1)
,(17,'DESENVOLVIMENTO DE PROJETO DE LONGA METRAGEM: ATÉ R$ 60.000,00',1)
,(17,'LANÇAMENTO DE OBRA DE LONGA METRAGEM EM 35MM: ATÉ R$ 110.000,00',1)
,(17,'FINALIZAÇÃO DE CURTA METRAGEM EM 35MM: ATÉ R$ 40.000,00',1)
,(17,'FINALIZAÇÃO DE CURTA METRAGEM EM DIGITAL ALTA DEFINIÇÃO: ATÉ R$ 10.000,00',1)
,(17,'AUTORAÇÃO/REPLICAGEM LONGA, MÉDIA OU CONJUNTO DE CURTA: ATÉ R$ 40.000,00',1)
,(17,'PROJETO MULTIÁREA: ATÉ R$ 150.000,00',1)
,(17,'VIDEODANÇA: ATÉ R$ 50.000,00',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'GRAVAÇÃO DE CD ? MÓDULO I: ATÉ R$ 20.000,00',1)
,(17,'CIRCULAÇÃO DF E ENTORNO: ATÉ R$ 60.000,00',1)
,(17,'GRAVAÇÃO DE CD ? MÓDULO III: ATÉ R$ 45.000,00',1)
,(17,'GRAVAÇÃO DE DVD: ATÉ R$ 120.000,00',1)
,(17,'GRAVAÇÃO DE VIDEOCLIPE: ATÉ R$ 50.000,00',1)
,(17,'PRÊMIOS E SALÕES - MÓDULO I:  ATÉ R$ 120.000,00',1)
,(17,'PRÊMIOS E SALÕES - MÓDULO II:  ATÉ R$ 300.000,00',1)
,(17,'EVENTOS (MOSTRAS, FESTIVAIS): ATÉ R$ 120.000,00',1)
,(17,'PROJETOS DE INCENTIVO À LEITURA EM MÍDIAS (SITES, RÁDIO, TV): ATÉ R$ 30.000,00',1)
,(17,'GRAVAÇÃO DE CD ? MÓDULO II: ATÉ R$ 35.000,00',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'CIRCULAÇÃO NACIONAL: ATÉ R$ 170.000,00',1)
,(17,'CIRCULAÇÃO REGIONAL: ATÉ R$ 120.000,00',1)
,(17,'FESTIVAIS, ENCONTROS E MOSTRAS - MÓDULO II: ATÉ R$ 150.000,00',1)
,(15,'Administração Direta / PRODEC',1)
,(17,'LANÇAMENTO DE CD/DVD: ATÉ R$ 30.000,00',1)
,(18,'Devolução Judicial',1)
,(17,'FAC/DIFUSÃO/PASSAGENS E DIÁRIAS: ATÉ R$ 10.000,00',1)
,(17,'FESTIVAIS, ENCONTROS E MOSTRAS - MÓDULO I: ATÉ R$ 50.000,00',1)
,(17,'FESTIVAIS, ENCONTROS E MOSTRAS - MÓDULO II: ATÉ R$ 140.000,00',1)
,(6,'Diligenciado - Projeto aprovado - (Solicitação de Documentos)',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(16,'Óperas e Musicais',1)
,(17,'CIRCULAÇÃO NACIONAL: ATÉ R$ 120.000,00',1)
,(17,'CIRCULAÇÃO REGIONAL: ATÉ R$ 90.000,00',1)
,(16,'Arte e Responsabilidade Social',1)
,(17,'FESTIVAIS, ENCONTROS E MOSTRAS - MÓDULO II: ATÉ R$ 60.000,00',1)
,(17,'FESTIVAIS, ENCONTROS E MOSTRAS - MÓDULO III: ATÉ R$ 150.000,00',1)
,(16,'Técnicos (cenotécnicos,  técnico de som, cenários, etc)',1)
,(17,'FORMAÇÃO E CAPACITAÇÃO DE PROFISSIONAIS ? MÓDULO I: ATÉ R$ 20.000,00',1)
,(17,'FORMAÇÃO E CAPACITAÇÃO DE PROFISSIONAIS ? MÓDULO I: ATÉ R$ 30.000,00',1)
,(17,'Projetos (coletivos, individuais, intervenções urb.) Módulo I',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'FORMAÇÃO E CAPACITAÇÃO DE PROFISSIONAIS ? MÓDULO II: ATÉ R$ 40.000,00',1)
,(17,'Prêmios e  Salões - Módulo I',1)
,(17,'Prêmios e  Salões - Módulo II',1)
,(17,'ENSINO DA ARTE/ENSINO DA ARTE E RESPONSABILIDADE SOCIAL ? MÓDULO I: ATÉ R$ 50.000,00',1)
,(17,'ENSINO DA ARTE/ENSINO DA ARTE E RESPONSABILIDADE SOCIAL ? MÓDULO II: ATÉ R$ 150.000,00',1)
,(17,'CAPACITAÇÃO PARA A GESTÃO CULTURAL ? MÓDULO I: ATÉ R$ 7.500,00',1)
,(17,'CAPACITAÇÃO PARA A GESTÃO CULTURAL ? MÓDULO I: ATÉ R$ 15.000,00',1)
,(17,'GESTÃO CONTINUADA (REDES, SISTEMAS DE INFORMAÇÃO): ATÉ R$ 120.000,00',1)
,(17,'PESQUISA (INDICADORES, ECONOMIA, PÚBLICO): ATÉ R$ 150.000,00',1)
,(17,'CONTADORES DE HISTÓRIAS: ATÉ R$ 6.000,00',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'MEDIADORES DE LEITURA: ATÉ R$ 6.000,00',1)
,(17,'OFICINAS DE CAPACITAÇÃO: ATÉ R$ 30.000,00',1)
,(17,'FORMAÇÃO DE MEDIADORES DE LEITURA: ATÉ R$ 160.000,00',1)
,(17,'PESQUISA, ELABORAÇÃO E DESENVOLVIMENTO DE OBRA LITERÁRIA: ATÉ R$ 20.000,00',1)
,(17,'FORMAÇÃO E CAPACITAÇÃO DE PROFISSIONAIS ? MÓDULO I: ATÉ R$ 15.000,00',1)
,(17,'Lançamento de Longa Metragem',1)
,(17,'EDUCAÇÃO PATRIMONIAL ? MÓDULO I: ATÉ R$ 50.000,00',1)
,(17,'EDUCAÇÃO PATRIMONIAL ? MÓDULO II: ATÉ R$ 150.000,00',1)
,(17,'PESQUISA: ATÉ R$ 300.000,00',1)
,(17,'Festivais, encontros e mostras',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Autoração/replicagem longa, média ou conjunto de curta',1)
,(17,'MANUTENÇÃO DE ESPAÇOS/COLETIVOS ? MÓDULO II: ATÉ R$ 100.000,00',1)
,(17,'MANUTENÇÃO DE ESPAÇOS/COLETIVOS ? MÓDULO I: ATÉ R$ 50.000,00',1)
,(17,'MANUTENÇÃO DE GRUPOS ? MÓDULO i: ATÉ R$ 80.000,00',1)
,(17,'MANUTENÇÃO DE GRUPOS ? MÓDULO I: ATÉ R$ 110.000,00',1)
,(17,'Circulação DF e Entorno',1)
,(17,'Circulação Regional',1)
,(17,'Circulação Nacional',1)
,(17,'Apoio a Temporada',1)
,(17,'MANUTENÇÃO DE GRUPOS ? MÓDULO III: ATÉ R$ 110.000,00',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'MANUTENÇÃO DE ESPAÇOS CULTURAIS MULTIÁREAS: ATÉ R$ 120.000,00',1)
,(17,'MANUTENÇÃO DE GRUPOS DE PESQUISA ? MÓDULO I: ATÉ R$ 80.000,00',1)
,(17,'MANUTENÇÃO DE GRUPOS DE PESQUISA ? MÓDULO II: ATÉ R$ 110.000,00',1)
,(17,'MANUTENÇÃO DE GRUPOS - MÓDULO I: ATÉ R$ 50.000,00',1)
,(17,'MANUTENÇÃO DE GRUPOS - MÓDULO III: ATÉ R$ 110.000,00',1)
,(20,'Patrocinador',1)
,(17,'INICIANTE: ATÉ R$ 20.000,00',1)
,(17,'MÓDULO I: ATÉ R$ 40.000,00',1)
,(17,'MÓDULO II: ATÉ R$ 80.000,00',1)
,(17,'MÓDULO III: ATÉ R$ 100.000,00',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'INICIANTE: ATÉ R$ 12.000,00',1)
,(17,'CATÁLOGO, LIVRO, PESQUISA, MEMÓRIA DE ARTES VISUAIS: ATÉ R$ 30.000,00',1)
,(17,'Desenvolvimento de obra literária',1)
,(17,'REGISTRO (CATÁLOGO, CD, LIVRO, SITE, ENTRE OUTROS): ATÉ R$ 30.000,00',1)
,(17,'Desenvolvimento de obras visuais',1)
,(17,'IMPRESSÃO DE LIVROS: ATÉ R$ 15.000,00',1)
,(17,'Festas e Celebrações',1)
,(17,'Festivais, encontros, mostras e calendário continuado de celebrações tradicionais',1)
,(17,'Apoio para montagem de Óperas e Musicais',1)
,(17,'IMPRESSÃO DE LIVRETOS (CORDEL): ATÉ R$ 3.000,00',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'IMPRESSÃO DE LIVROS ? MÓDULO INICIANTES: ATÉ R$ 12.000,00',1)
,(17,'Arte e responsabilidade social',1)
,(17,'Capacitação local',1)
,(17,'Capacitação nacional',1)
,(17,'Catálogo, livro, pesquisa, memória de Artes visuais Módulo I',1)
,(17,'Catálogo, livro, pesquisa, memória de Artes visuais Módulo II',1)
,(17,'Circuito de Feiras',1)
,(17,'Contadores de Histórias',1)
,(17,'Desenvolvimento de projeto de longa documentário',1)
,(8,'Diligência na avaliação - Relatório Final',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(8,'Diligência de Checklist - Análise',1)
,(8,'Diligência de Checklist - Readequação',1)
,(16,'Artes Visuais',1)
,(16,'Cinema',1)
,(16,'Dança',1)
,(16,'Música',1)
,(16,'Circo',1)
,(16,'Cultura Popular',1)
,(16,'Diversidade',1)
,(16,'Literatura',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(16,'Passagens',1)
,(16,'Patrimônio',1)
,(16,'Teatro',1)
,(16,'Ensino da Arte / Responsabilidade Social',1)
,(16,'Gestão Cultural',1)
,(16,'Espaços Culturais',1)
,(15,'Fundo de Apoio à Cultura - GDF',1)
,(17,'REALIZAÇÃO DE CURTA METRAGEM EM DIGITAL ALTA DEFINIÇÃO ? INICIANTES: ATÉ R$ 20.000,00',1)
,(15,'Programa Museu, Memória e Cidadania (Ibram)',1)
,(18,'Devolução ao Fundo Nacional de Cultura - FNC',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(16,'Circuitos',1)
,(16,'Eventos Consolidados',1)
,(16,'Bolsas de Estudos',1)
,(16,'Patrimônio Histórico Material e Imaterial',1)
,(16,'Gestão Cultural',1)
,(17,'FESTIVAIS, ENCONTROS E MOSTRAS - MÓDULO I: ATÉ R$ 80.000,00',1)
,(19,'Inicial',1)
,(19,'Readequação',1)
,(17,'TEMPORADA: ATÉ R$ 15.000,00',1)
,(17,'EVENTOS CULTURA E DIVERSIDADE - MÓDULO I: ATÉ R$ 30.000,00',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'EVENTOS CULTURA E DIVERSIDADE - MÓDULO II: ATÉ R$ 60.000,00',1)
,(17,'EVENTOS CULTURA E DIVERSIDADE - MÓDULO III: ATÉ R$ 150.000,00',1)
,(17,'CONCURSO LITERÁRIO REGIONAL E NACIONAL (CONTOS, CRÔNICAS, POEMAS): ATÉ R$ 150.000,00',1)
,(19,'Recurso',1)
,(17,'Projetos (coletivos, individuais, intervenções urb.) Módulo II',1)
,(17,'FESTIVAIS, ENCONTROS E MOSTRAS - MÓDULO III: ATÉ R$ 250.000,00',1)
,(17,'LANÇAMENTO DE LIVRO: ATÉ R$ 12.500,00',1)
,(17,'APOIO PARA MONTAGEM DE OPERETAS E MUSICAIS: ATÉ R$ 160.000,00',1)
,(17,'Evento literário (concursos,feiras, encontros, seminários) Módulo II',1)
,(17,'Evento literário (feiras, encontros, seminários) Módulo I',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Eventos (mostras e festivais) Módulo I',1)
,(17,'Eventos (mostras e festivais) Módulo II',1)
,(17,'Festivais mostras, seminários, foruns - Módulo I',1)
,(17,'Festivais mostras, seminários, foruns - Módulo II',1)
,(17,'Finalização de curta metragem com masterização em DCP',1)
,(17,'Finalização de longa metragem ficção, animação e doc 35mm',1)
,(17,'Formação de Mediadores de Leitura e/ou Contadores de Histórias',1)
,(17,'Gravação de Álbum',1)
,(17,'Impressão de livretos (cordel) Módulo I',1)
,(17,'Impressão de livros -  Módulo I',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Impressão de livros -  Módulo Iniciantes',1)
,(17,'Impressão de livros - Módulo II',1)
,(17,'Impressão de periódicos (revistas, jornais)',1)
,(17,'Lançamento e Distribuição de CD/DVD',1)
,(17,'Lançamento e Distribuição de Livro',1)
,(17,'Manutenção de Espaços',1)
,(17,'Manutenção de Espaços/coletivos - Módulo I',1)
,(17,'Manutenção de Espaços/coletivos - Módulo II',1)
,(17,'Manutenção de grupo Módulo I',1)
,(17,'Manutenção de grupo Módulo II',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Manutenção de grupos de pesquisa Módulo I',1)
,(17,'Manutenção de grupos de pesquisa Módulo II',1)
,(17,'Mediadores de Leitura',1)
,(17,'Montagem de Espetáculo Módulo I',1)
,(17,'Montagem de Espetáculo Iniciante',1)
,(17,'Montagem de Espetáculo Módulo II',1)
,(17,'Multiárea',1)
,(17,'Produção longa de Ficção e Animação em 35mm e/ou DCP',1)
,(17,'Produção longa-metragem de documentário em 35mm e/ou DCP',1)
,(17,'Projetos de incentivo a leitura em mídias',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Publicações/registro  (catálogo, CD,  livro, site)',1)
,(17,'Realização de curta metragem em 35mm e/ou DCP',1)
,(17,'Realização de curta metragem em HD  Estreantes',1)
,(17,'Realização de obra radiofônica - rádio documentário',1)
,(17,'Realização de obra radiofônica - revista de jornalismo cultural',1)
,(17,'Realização de Projeto de série de TV DOC ou Ficção (Bíblia e Piloto)',1)
,(17,'Realização de série radiofônica - rádio conto',1)
,(16,'Audiovisual',1)
,(20,'Proponente',1)
,(17,'Digitalização e/ou Tratamento de Acervo: até R$ 50.000,00',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Circulação de Exposição Individual ou Coletiva: até R$ 50.000,00',1)
,(16,'Registro e Memória',1)
,(17,'Apoio para montagem de Óperas e Musicais ? Módulo I',1)
,(17,'Apoio para montagem de Óperas e Musicais ? Módulo II',1)
,(17,'Arte e responsabilidade social - Módulo I',1)
,(17,'Arte e responsabilidade social - Módulo II',1)
,(17,'Artes Visuais',1)
,(17,'Biblioteca Nacional',1)
,(17,'Calendário continuado de celebrações tradicionais',1)
,(17,'Capacitação em Elaboração e Gestão de Projetos',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Capacitação nacional e/ou internacional',1)
,(17,'Cinema',1)
,(17,'Cultura nos Trilhos',1)
,(17,'Cultura Popular & Circo',1)
,(17,'Desenvolvimento de Projeto de longa-metragem',1)
,(17,'Temporadas de Sol',1)
,(17,'Teatro',1)
,(17,'Digitalização e/ou tratamento de acervos bibliográficos e gráficos',1)
,(17,'Festas e Celebrações Tradicionais',1)
,(17,'Festas, Festivais e mostras com mais de 10 anos',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Festas, Festivais e mostras com mais de 5 anos',1)
,(17,'Festejos do ciclo Natalino e Junino nas Regiões Administrativas',1)
,(17,'Festivais, encontros e mostras Cine Brasília',1)
,(17,'Finalização de curta metragem com masterização em DCP',1)
,(17,'Finalização de longa metragem ficção, animação e doc 35mm',1)
,(17,'Galeria Athos Bulcão',1)
,(17,'Gravação de Álbum - Módulo I (iniciantes)',1)
,(17,'Gravação de Álbum - Módulo II',1)
,(17,'Gravação de DVD',1)
,(17,'Gravação de Videoclipe',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Impressão de catálogo e livro de Pesquisa',1)
,(17,'Literatura',1)
,(17,'Museu Sonoro',1)
,(17,'Música',1)
,(17,'Pesquisa aspectos socioeconômicos da cultura',1)
,(17,'Pesquisa inventário de bem imaterial',1)
,(17,'Prêmios e Salões - Módulo III',1)
,(17,'Produção longa de Ficção e Animação com finalização digital',1)
,(17,'Produção longa-metragem de documentário com finalização digital',1)
,(17,'Projeto de disponibilização de acervo',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Projeto de publicação (livro, catálogo, site, CD)',1)
,(17,'Projeto Educativo para Dança',1)
,(17,'Projeto Educativo para Museu da República',1)
,(17,'Projeto Educativo para Museus Históricos',1)
,(17,'Projeto Educativo para Música  nas Escolas',1)
,(17,'Projeto Educativo para Teatro',1)
,(17,'Projetos (coletivos, individuais, intervenções urb.)',1)
,(17,'Projetos de Acessbilidade a obras artísticas e culturais',1)
,(17,'Projetos Módulo I (Iniciantes)',1)
,(17,'Projetos Módulo II',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Restauro de obras artísticas e museológicas',1)
,(16,'Dança, Circo, Cultura Pop., Literatura, Música, Teatro',1)
,(17,'CIRCULAÇÃO DF E ENTORNO: ATÉ R$ 40.000,00',1)
,(17,'MANUTENÇÃO DE GRUPOS ? MÓDULO II: ATÉ R$ 80.000,00',1)
,(17,'FORMAÇÃO E CAPACITAÇÃO DE PROFISSIONAIS ? MÓDULO II: ATÉ R$ 30.000,00',1)
,(17,'FORMAÇÃO E CAPACITAÇÃO DE PROFISSIONAIS ? MÓDULO II: ATÉ R$ 15.000,00',1)
,(17,'FESTIVAIS, ENCONTROS E MOSTRAS - MÓDULO II: ATÉ R$ 180.000,00',1)
,(17,'FESTIVAIS, ENCONTROS E MOSTRAS - MÓDULO III: ATÉ R$ 220.000,00',1)
,(17,'FORMAÇÃO E CAPACITAÇÃO DE PROFISSIONAIS ? MÓDULO II: ATÉ R$ 7.500,00',1)
,(20,'Beneficiário',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(16,'Circulação ? Artes Visuais',1)
,(16,'Dança, Circo, Cultura Pop., Teatro',1)
,(16,'Diversidade/Acessibilidade',1)
,(16,'Eventos Consolidados',1)
,(16,'Ocupação',1)
,(16,'Panoramas',1)
,(16,'Rádio',1)
,(16,'Todas as Áreas / Linguagens',1)
,(16,'Todas as Áreas/Lingugens, exceto Literatura e Patrimônio',1)
,(17,'Publicações/Registro (CD, livro, site)',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Disponibilização de acervo',1)
,(16,'Economia Criativa',1)
,(16,'Ponto de Cultura',1)
,(8,'Diligência no Recurso - Parecerista',1)
,(8,'Diligência no Recurso - CNIC',1)
,(8,'Diligência no Recurso - Técnico',1)
,(21,'Agência Bancária',1)
,(21,'Sinópse da Obra',1)
,(21,'Impacto Ambiental',1)
,(21,'Especificação Técnica',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(21,'Estratégia de Execução',1)
,(21,'Local de Realização',1)
,(21,'Alteração de Proponente',1)
,(21,'Alteração de Razão Social',1)
,(21,'Plano de Distribuição',1)
,(21,'Planilha Orçamentária',1)
,(21,'Nome do Projeto',1)
,(21,'Período de Execução',1)
,(21,'Plano de Divulgação',1)
,(21,'Resumo do Projeto',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(21,'Objetivos',1)
,(21,'Justificativa',1)
,(21,'Acessibilidade',1)
,(21,'Democratização de Acesso',1)
,(21,'Etapas de Trabalho',1)
,(21,'Ficha Técnica',1)
,(17,'Credenciamento',1)
,(6,'Projeto avaliado na reunião da Comissão Nacional de Incentivo à Cultura (CNIC). ',1)
,(21,'Readequação até 20%',1)
,(16,'Livro, Leitura e Literatura',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(6,'EDITAL - Confirmação do recebimento no Ministério da Cultura',1)
,(22,'001 - Tipo pessoa inválido',1)
,(22,'002 - Tipo CPF/CNPJ inválido',1)
,(22,'003 - CPF/CNPJ inválido',1)
,(22,'004 - Data nascimento inválida',1)
,(22,'005 - Nome cliente inválido',1)
,(22,'006 - Agência/dv inválido',1)
,(22,'007 - Mais de 5 clientes cadastrados para CPF informado',1)
,(22,'008 - Cliente BB-Campus fora da faixa etária (16 a 28 anos)',1)
,(22,'009 - Cliente BB-Campus não é pessoa física',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(22,'010 - Dados da pessoa física divergentes com a Receita Federal',1)
,(22,'011 - Dados da pessoa jurídica divergentess com a Receita Federal',1)
,(22,'013 - Cliente BB-Campus não é o titular do CPF',1)
,(22,'014 - Perfil da agência incompatível com o tipo de pessoa',1)
,(22,'015 - Tipo de pessoa incompatível com a natureza jurídica',1)
,(22,'016 - Tipo de repasse inválido',1)
,(22,'017 - Tipo de pessoa não permitido para esse processo/tipo de repasse',1)
,(6,'Comunicado de encerramento do prazo de prestação de contas',1)
,(23,'Projeto normal',1)
,(23,'Proteção do patrimônio material',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(23,'Proteção do patrimônio imaterial',1)
,(23,'Proteção  de acervos',1)
,(23,'Planos anuais',1)
,(23,'Projeto museológico',1)
,(23,'Projeto de manutenção de corpos estáveis',1)
,(23,'Projeto de construção de equipamentos culturais',1)
,(23,'Projeto aprovado em editais',1)
,(23,'Projeto  com contratos de patrocínios',1)
,(6,'Enquadramento de projeto cultural',1)
,(24,'Parecer de Avaliação do Objeto',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(24,'Parecer de Avaliação Financeira',1)
,(24,'Laudos de Prestação de Contas',1)
,(24,'Portarias',1)
,(24,'Parecer de Aprovação Preliminar',1)
,(6,'Liberação do período para adequação do projeto à realidade de execução',1)
,(24,'Análise Técnica para Homologação de Projeto',1)
,(24,'Apreciação para Homologação de Projeto',1)
,(25,'Admissibilidade',1)
,(25,'Aprovação',1)
,(25,'Análise Técnica',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(25,'Apreciação da Cnic',1)
,(25,'Homologação para Execução',1)
,(25,'Movimentação Bancária',1)
,(25,'Readequação',1)
,(25,'Fiscalização',1)
,(25,'Comprovação',1)
,(25,'Avaliação de Resultado',1)
,(24,'Homologação para Execução do Projeto',1)
,(24,'Parecer Técnico de Readequação de Projeto -Vinculadas',1)
,(24,'Parecer Técnico de Ajuste de Projeto',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(24,'Readequação - Planilha Orçamentária',1)
,(24,'Readequação - Alteração de Razão Social',1)
,(24,'Readequação - Agência Bancária',1)
,(24,'Readequação - Sinópse da Obra',1)
,(24,'Readequação - Impacto Ambiental',1)
,(24,'Readequação - Especificação Técnica',1)
,(24,'Readequação - Estratégia de Execução',1)
,(24,'Readequação - Local de Realização',1)
,(24,'Readequação - Alteração de Proponente',1)
,(24,'Readequação - Plano de Distribuição',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(24,'Readequação - Nome do Projeto',1)
,(24,'Readequação - Período de Execução',1)
,(24,'Readequação - Plano de Divulgação',1)
,(24,'Readequação - Resumo do Projeto',1)
,(24,'Readequação - Objetivos',1)
,(24,'Readequação - Justificativa',1)
,(24,'Readequação - Acessibilidade',1)
,(24,'Readequação - Democratização de Acesso',1)
,(24,'Readequação - Etapas de Trabalho',1)
,(24,'Readequação - Ficha Técnica',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(24,'Readequação - Saldo de Aplicação',1)
,(24,'Readequação - Transferência de recursos entre projetos
Transferência de recursos entre projetos',1)
,(24,'Fiscalização',1)
,(17,'IMPRESSÃO DE LIVROS ? MÓDULO I: ATÉ R$ 15.000,00',1)
,(17,'IMPRESSÃO DE LIVROS ? MÓDULO II: ATÉ R$ 20.000,00',1)
,(17,'IMPRESSÃO DE LIVROS ? MÓDULO III: ATÉ R$ 25.000,00',1)
,(17,'IMPRESSÃO DE PERIÓDICOS (REVISTAS, JORNAIS, HISTÓRIA EM QUADRINHOS, ENTRE OUTROS): ATÉ R$ 90.000,00',1)
,(17,'MÍDIAS ELETRÔNICAS (E-BOOKS, ENTRE OUTROS): ATÉ R$ 10.000,00',1)
,(17,'Apoio a eventos do calendário (até R$ 100.000,00)',1)
,(17,'Apoio a Temporada (até R$ 30.000,00)',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Arte e responsabilidade social - Módulo I (até R$ 80.000,00)',1)
,(17,'Arte e responsabilidade social - Módulo II (até R$ 150.000,00)',1)
,(17,'Biblioteca Viva (até R$ 30.000,00)',1)
,(17,'Bolsa de Estudo internacional (até R$ 60.000,00)',1)
,(17,'PROJETOS  - INICIANTES : ATÉ R$ 20.000,00',1)
,(17,'PROJETOS  - MÓDULO I : ATÉ R$ 50.000,00',1)
,(17,'PROJETOS  - MÓDULO II : ATÉ R$ 80.000,00',1)
,(17,'PROJETOS  - MÓDULO III : ATÉ R$ 150.000,00',1)
,(17,'Bolsa de Estudo local (até R$ 20.000,00)',1)
,(17,'Bolsa de Estudo nacional (até R$ 36.000,00)',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Capacitação em Elaboração e Gestão de Projetos (até R$ 150.000,00)',1)
,(17,'Capacitação local (até R$ 30.000,00)',1)
,(17,'Capacitação nacional (até R$ 50.000,00)',1)
,(17,'Capacitação nacional (até R$ 80.000,00)',1)
,(17,'Circulação DF e Entorno (até R$ 150.000,00)',1)
,(17,'Cultura nos Trilhos (até R$ 50.000,00)',1)
,(26,'Elaboração e sugestão de enquadramento da proposta cultural',1)
,(17,'Desenvolvimento de site sobre produção cinematográfica em BSB (até R$ 50.000,00)',1)
,(17,'Digitalização e/ou tratamento de acervos bibliográficos e gráficos (até R$ 80.000,00)',1)
,(17,'Digitalização e/ou tratamento de acervos em audiovisual (até R$ 80.000,00)',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Eixão Cultural (até R$ 80.000,00)',1)
,(17,'Espaços Teatrais (até R$ 90.000,00)',1)
,(17,'Eventos  (até R$ 150.000,00)',1)
,(17,'Festas, Festivais e mostras com mais de 10 anos (até R$ 500.000,00)',1)
,(17,'Festas, Festivais e mostras com mais de 5 anos (até R$ 250.000,00)',1)
,(17,'Festejos do ciclo Natalino e Junino nas Regiões Administrativas (até R$ 40.000,00)',1)
,(17,'Formação de Jovens Agentes de Cultura (até R$ 30.000,00)',1)
,(17,'Formação e capacitação de profissionais - Módulo I (até R$ 15.000,00)',1)
,(17,'Formação e capacitação de profissionais - Módulo II (até R$ 30.000,00)',1)
,(17,'Gravação de Álbum - Módulo I (até R$ 20.000,00)',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Gravação de Álbum - Módulo II  (até R$ 45.000,00)',1)
,(17,'Gravação de DVD (até R$ 120.000,00)',1)
,(17,'Gravação de Videoclipe (até R$ 50.000,00)',1)
,(17,'Montagem  de Espetáculos - Módulo I (até R$ 40.000,00)',1)
,(17,'Montagem  de Espetáculos - Módulo II (até R$ 80.000,00)',1)
,(17,'Montagem de Opereta e Musicais (até R$ 160.000,00)',1)
,(17,'Multiárea (até R$ 250.000,00)',1)
,(17,'Museu Sonoro (até R$ 80.000,00)',1)
,(17,'Pesquisa  Módulo II - áreas de memória (até R$ 350.000,00)',1)
,(17,'Pesquisa Módulo I - inventário de bem imaterial (até R$ 150.000,00)',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Projeto de disponibilização de acervo (até R$ 50.000,00)',1)
,(17,'Projeto Educativo para Dança (até R$ 60.000,00)',1)
,(17,'Projeto Educativo para Museu da República (até R$ 320.000,00)',1)
,(17,'Projeto Educativo para Museus Históricos - 3 poderes (até R$ 350.000,00)',1)
,(17,'Projeto Educativo para Museus Históricos - MVMC (até R$ 350.000,00)',1)
,(17,'Projeto Educativo para Música de Câmara nas Escolas (até R$ 70.000,00)',1)
,(17,'Projeto Educativo para Música de Orquestra no Teatro (até R$ 600.000,00)',1)
,(17,'Projeto Educativo para o Museus Históricos - Catetinho (até R$ 350.000,00)',1)
,(17,'Projeto Educativo para Teatro (até R$ 60.000,00)',1)
,(17,'Projetos de Acessbilidade a obras artísticas e culturais (até R$ 200.000,00)',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(17,'Temporadas de Sol (até R$ 120.000,00)',1)
,(26,'Comprovação de capacidade de execução',1)
,(26,'Avaliação técnica do projeto cultural',1)
,(26,'Atingimento de captação para liberar a execução do projeto',1)
,(26,'Execução do projeto e comprovação dos gastos efetuados',1)
,(26,'Avaliação dos resultados da ação cultural',1)
,(26,'Projeto cultural encerrado',1)
,(18,'Outras Devoluções de recursos captados',1)
,(15,'Fomento a projetos, eventos e intercâmbio na área museológica',1)
,(24,'Comunicados',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(6,'Lançamento automático de solicitação de prorrogação de prazo para captar recursos',1)
,(17,'Biblioteca Viva',1)
,(17,'Acessibilidade a Obras Artísticas e Culturais',1)
,(17,'Projeto Educativo para o Museu Histórico MVMC (visita orientada)',1)
,(17,'Apoio a Eventos do Calendário',1)
,(8,'Diligência de notificação de cobrança de prestação de contas',1)
,(27,'Fase do projeto',1)
,(27,'Ultrapassou a métrica de custo do item orçamentário',1)
,(27,'Bilheteria / custo do projeto',1)
,(27,'Custo percapto',1)
;
INSERT INTO SAC.dbo.Verificacao (idTipo,Descricao,stEstado) VALUES 
(27,'Regularidade do projeto',1)
,(27,'Nivel de comprovação',1)
,(27,'Concentração de fornecedores',1)
,(27,'Tempo de execução do projeto',1)
,(6,'Encerramento do período de adequação do projeto à realidade de execução.',1)
,(25,'Regularidade',1)
,(8,'Diligência na Prestação de contas - Todos os itens',1)
,(24,'Parecer Técnico de Readequação de Projeto - MinC',1)
;